/* ============================================================
   Career Destiny — Data Layer
   MBTI quiz, job positions, majors, skills, roadmaps
   ============================================================ */

// ── Grade Options ────────────────────────────
const GRADE_OPTIONS = [
  '大一', '大二', '大三', '大四',
  '研一', '研二', '研三',
  '博士在读', '已毕业(应届)', '已毕业(往届)',
];

// ── Major Categories ─────────────────────────
const MAJOR_LIST = [
  // 计算机/电子
  '计算机科学与技术', '软件工程', '人工智能', '数据科学与大数据技术',
  '电子信息工程', '通信工程', '自动化', '网络空间安全', '物联网工程',
  // 商科/管理
  '工商管理', '市场营销', '会计学', '财务管理', '人力资源管理',
  '国际经济与贸易', '金融学', '经济学', '信息管理与信息系统',
  // 文科/社科
  '汉语言文学', '新闻传播学', '广告学', '英语', '日语', '法学',
  '社会学', '心理学', '教育学', '行政管理', '公共管理',
  // 理科/工科
  '数学与应用数学', '统计学', '物理学', '化学',
  '机械工程', '电气工程', '土木工程', '材料科学', '能源与动力工程',
  '生物医学工程', '环境工程',
  // 设计/艺术
  '视觉传达设计', '数字媒体艺术', '工业设计', '动画',
  // 医学/生命科学
  '临床医学', '药学', '生物技术', '生物信息学',
  // 其他
  '其他工科', '其他理科', '其他文科', '其他商科',
];

// ── Skill Tags ───────────────────────────────
const SKILL_TAGS = [
  'Python', 'Java', 'C/C++', 'JavaScript', 'SQL', 'R语言', 'Go', 'Rust',
  '机器学习', '深度学习', '数据分析', '数据可视化',
  'Excel', 'PPT', 'Word',
  '英语六级', '英语专八', '日语N1', '韩语',
  '视频剪辑', 'Photoshop', 'Figma', 'AE特效',
  '写作', '演讲', '谈判', '项目管理', '团队管理',
  '用户研究', '产品设计', 'Axure', 'Figma',
  '财会基础', 'CPA', 'CFA', '法考',
];

// ── Industry Directions ──────────────────────
const INDUSTRY_TAGS = [
  '互联网/科技', '金融/投资', '公务员/事业编', '国企/央企',
  '快消/零售', '咨询/四大', '制造业', '教育/培训',
  '医疗/医药', '广告/传媒', '房地产/建筑', '新能源/汽车',
  '游戏/娱乐', '创业/Startup',
];

// ── Priority Options ─────────────────────────
const PRIORITY_OPTIONS = [
  { id: 'salary', label: '薪资待遇', desc: '起薪高，涨幅快，财务自由是首要目标' },
  { id: 'growth', label: '成长空间', desc: '能学到东西，晋升通道清晰，长期发展好' },
  { id: 'stability', label: '工作稳定', desc: '不怕裁员，工作生活平衡，安心过日子' },
  { id: 'culture', label: '团队氛围', desc: '同事好相处，领导靠谱，每天上班不痛苦' },
  { id: 'impact', label: '社会影响力', desc: '做的事情有意义，能改变人们的生活' },
  { id: 'tech', label: '技术深度', desc: '能深耕一个领域，成为不可替代的专家' },
];

// ── MBTI Quiz Questions (8 questions, 4 dimensions) ────
// Dimensions: IE (内向/外向), TF (理性/感性), JP (规划/随性), SN (务实/创新)

const QUIZ_QUESTIONS = [
  {
    id: 1,
    text: '周五晚上，结束了一周的忙碌，你更想？',
    narrative: '终于到周末了，你合上电脑，感到一阵释放——',
    choices: [
      { text: '约上朋友们出去聚会、吃饭、嗨一晚上', icon: '🦋', effect: { IE: 2, SN: 1 } },
      { text: '一个人在家看看书、追个剧，安静恢复', icon: '🌙', effect: { IE: -2, JP: 1 } },
      { text: '和一两个要好的朋友小聚，聊到深夜', icon: '🌿', effect: { TF: 1, IE: 1 } },
      { text: '取决于这周累不累，看心情决定', icon: '🍃', effect: { JP: -2, TF: 1 } },
    ],
  },
  {
    id: 2,
    text: '做小组作业时，你更在意什么？',
    narrative: '群里又弹出消息，项目还剩三天deadline——',
    choices: [
      { text: '分工明确，按时交付，别拖我后腿', icon: '⚡', effect: { JP: 2, TF: 1 } },
      { text: '大家关系和谐，别因为作业伤感情', icon: '💧', effect: { TF: -2, IE: 1 } },
      { text: '做出来的东西够不够酷，有没有新意', icon: '🔥', effect: { SN: 2, JP: -1 } },
      { text: '有一个清晰的框架，然后各自执行', icon: '🗂️', effect: { JP: 1, SN: -1, TF: 1 } },
    ],
  },
  {
    id: 3,
    text: '你有一个月的空闲时间，你会？',
    narrative: '寒假/暑假来了，没有作业，没有实习，完全由你支配——',
    choices: [
      { text: '排满计划：学技能、考证、健身，每天都有目标', icon: '📋', effect: { JP: 2, SN: -1 } },
      { text: '随性安排，今天想做什么就做什么', icon: '🎈', effect: { JP: -2, IE: 1 } },
      { text: '旅行、见人、体验各种新鲜事物', icon: '✈️', effect: { SN: 2, IE: 2 } },
      { text: '深度钻研一个自己感兴趣的领域', icon: '🔬', effect: { SN: 1, IE: -1, TF: 1 } },
    ],
  },
  {
    id: 4,
    text: '看到一个全新的工具或技术，你的第一反应是？',
    narrative: '朋友圈刷到有人分享了一个你觉得挺有意思的东西——',
    choices: [
      { text: '立刻上手试试，边用边学', icon: '🚀', effect: { SN: 2, JP: -1 } },
      { text: '先查资料看评价，确认有用再学', icon: '📚', effect: { JP: 2, SN: -1, TF: 1 } },
      { text: '想想它对我目前的项目有没有实际帮助', icon: '🎯', effect: { TF: 2, SN: -1 } },
      { text: '转发给朋友讨论，听听他们怎么看', icon: '💬', effect: { IE: 2, TF: -1 } },
    ],
  },
  {
    id: 5,
    text: '面对一个重要的人生选择，你更相信？',
    narrative: '站在岔路口，你手里有数据、有前辈的建议、也有自己的直觉——',
    choices: [
      { text: '数据和分析，让事实说话', icon: '📊', effect: { TF: 2, SN: -1 } },
      { text: '内心的感觉，什么让你真正兴奋', icon: '❤️', effect: { TF: -2, SN: 1 } },
      { text: '身边信任的人的建议和判断', icon: '🤝', effect: { IE: 1, TF: -1 } },
      { text: '先列个pros & cons清单，权衡利弊', icon: '⚖️', effect: { JP: 2, TF: 1 } },
    ],
  },
  {
    id: 6,
    text: '在一个团队里，你习惯的角色是？',
    narrative: '新的项目组成立了，你环顾一圈，心里想——',
    choices: [
      { text: '站出来组织、推动、拍板的那个', icon: '👑', effect: { IE: 2, JP: 1 } },
      { text: '在幕后分析、规划、确保不出错的那个', icon: '🦉', effect: { IE: -1, JP: 2, TF: 1 } },
      { text: '提供奇思妙想、打破常规的那个', icon: '🎨', effect: { SN: 2, TF: -1 } },
      { text: '调和气氛、关心每个人状态的那个', icon: '☕', effect: { TF: -2, IE: 1 } },
    ],
  },
  {
    id: 7,
    text: '面试官问你："你最大的缺点是什么？"你心里真正想的是？',
    narrative: '这道题的标答你背过，但此刻你决定对自己诚实一次——',
    choices: [
      { text: '我有时太追求完美，对自己和他人要求太高', icon: '💎', effect: { JP: 2, TF: 1 } },
      { text: '我不太擅长拒绝别人，容易承担过多', icon: '🕊️', effect: { TF: -2, IE: 1 } },
      { text: '我不喜欢按部就班，总觉得有更好的方法', icon: '🌪️', effect: { SN: 2, JP: -2 } },
      { text: '我更愿意独处，不太适应频繁的社交场合', icon: '🏔️', effect: { IE: -2, SN: -1 } },
    ],
  },
  {
    id: 8,
    text: '三年后，你希望自己的生活状态是？',
    narrative: '最后一个问题——闭上眼睛，想象三年后的某个普通周二——',
    choices: [
      { text: '在大城市的核心团队里，做着有挑战的项目，每天都在成长', icon: '🏙️', effect: { IE: 1, SN: 1, JP: 1 } },
      { text: '有一份稳定体面的工作，下班有时间陪家人、发展爱好', icon: '🏡', effect: { IE: -1, JP: 2, SN: -1 } },
      { text: '说不准，可能在创业，可能在旅居，但一定在做自己热爱的事', icon: '🌈', effect: { SN: 2, JP: -2, TF: -1 } },
      { text: '身边有一群志同道合的人，我们在一起做着有意义的事', icon: '🌻', effect: { TF: -2, IE: 2, SN: 1 } },
    ],
  },
];

// ── Job Positions Database (15 jobs, 6 industries) ────

const JOB_DATABASE = [
  {
    id: 'product-manager',
    title: '产品经理',
    industry: '互联网/科技',
    salary: '15-25K (应届)', salaryRange: '应届15-25K → 3年25-40K → 5年40-70K',
    tags: ['产品设计', '用户研究', '数据分析', '项目管理'],
    matchProfile: { IE: 1, TF: -1, JP: 1, SN: 1 },
    icon: '📱',
    description: '负责定义产品方向、设计产品功能、推动产品从0到1落地。需要理解用户需求、分析市场趋势、协调研发/设计/运营团队。',
    personality: '适合既有大局观又能关注细节的人。E型适合频繁沟通推进，I型适合深度思考产品逻辑；N型带来创新思维，S型保证落地执行。',
    dayInLife: '09:30 站会同步进度 → 10:00 看数据/竞品分析 → 14:00 原型设计/PRD撰写 → 16:00 跨部门沟通 → 19:00 用户访谈/复盘',
    companies: '腾讯、阿里巴巴、字节跳动、美团、拼多多、京东、百度',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['阅读《启示录》《结网》等产品入门书', '学习使用 Axure/Figma 画原型', '选修心理学、社会学相关课程', '参加产品类社团或比赛(PM Hackathon)'] },
      sophomore: { title: '大二·基础期', items: ['深入学习 SQL + Excel 数据分析', '自己设计一个小产品并写完整PRD', '参加"互联网+"等创业比赛', '找一份产品助理实习(暑期)'] },
      junior: { title: '大三·实战期', items: ['系统学习 A/B测试、用户研究 方法论', '至少1段大厂产品实习经历', '建立自己的产品分析作品集', '刷牛客/力扣产品题，准备秋招'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递30+公司', '持续跟进产品动态(36氪/虎嗅)', '开始带新人或独立own一个小功能', '准备毕业设计(最好与产品方向相关)'] },
    },
    skills: [
      { name: 'SQL/数据分析', type: 'required', desc: '能独立写SQL取数分析' },
      { name: '原型设计 (Axure/Figma)', type: 'required', desc: '能快速产出高保真原型' },
      { name: 'PRD撰写', type: 'required', desc: '能写清晰完整的需求文档' },
      { name: '用户研究', type: 'recommended', desc: '访谈、问卷、可用性测试' },
      { name: 'A/B测试', type: 'recommended', desc: '实验设计与数据分析' },
      { name: '基础编程理解', type: 'recommended', desc: '理解技术实现逻辑即可' },
      { name: '商业分析', type: 'advanced', desc: '行业研究、竞品分析框架' },
      { name: '项目管理(PMP)', type: 'advanced', desc: '敏捷开发、Scrum流程' },
    ],
  },
  {
    id: 'frontend-dev',
    title: '前端开发工程师',
    industry: '互联网/科技',
    salary: '14-24K (应届)', salaryRange: '应届14-24K → 3年22-40K → 5年35-65K',
    tags: ['HTML/CSS', 'JavaScript', 'React/Vue', 'Node.js'],
    matchProfile: { IE: -1, TF: 1, JP: 1, SN: -1 },
    icon: '💻',
    description: '负责Web/移动端页面的开发实现，将设计稿转化为用户可直接交互的界面。需要扎实的编程基础和对用户体验的理解。',
    personality: '适合喜欢"即时反馈"的人——写完代码立刻能看到效果。S型适合关注细节和交互体验，T型在调试和逻辑处理上有优势。',
    dayInLife: '10:00 站会 → 10:30 写代码/Code Review → 14:00 技术方案讨论 → 16:00 继续开发/修Bug → 19:00 技术分享/学习新技术',
    companies: '字节跳动、腾讯、阿里巴巴、美团、百度、小红书、B站',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习 HTML/CSS，能还原静态页面', '学习 JavaScript 基础语法', '用 Git 管理代码，注册 GitHub', '完成一个小型个人网站'] },
      sophomore: { title: '大二·基础期', items: ['深入学习 JS(ES6+)、异步编程', '学习一个前端框架(React或Vue)', '学习 Node.js 基础', '做2-3个完整项目放GitHub'] },
      junior: { title: '大三·实战期', items: ['深入框架原理(虚拟DOM/状态管理)', '学习 TypeScript', '学习前端工程化(Webpack/Vite)', '暑期找一份前端实习'] },
      senior: { title: '大四·冲刺期', items: ['刷 LeetCode (200+题)', '整理项目经验和面试题', '秋招投递，同时准备春招补录', '关注前端新技术(AI编程/WebAssembly)'] },
    },
    skills: [
      { name: 'HTML/CSS/JS', type: 'required', desc: '前端三件套基础扎实' },
      { name: 'React 或 Vue', type: 'required', desc: '至少精通一个主流框架' },
      { name: 'Git 版本管理', type: 'required', desc: '日常协作必备' },
      { name: 'TypeScript', type: 'recommended', desc: '大厂普遍使用' },
      { name: 'Node.js', type: 'recommended', desc: '理解后端，能写BFF层' },
      { name: 'Webpack/Vite', type: 'recommended', desc: '工程化构建工具' },
      { name: '算法与数据结构', type: 'required', desc: '面试必考' },
      { name: '跨端开发(Flutter/RN)', type: 'advanced', desc: '移动端能力扩展' },
    ],
  },
  {
    id: 'data-analyst',
    title: '数据分析师',
    industry: '互联网/科技',
    salary: '12-22K (应届)', salaryRange: '应届12-22K → 3年20-35K → 5年30-55K',
    tags: ['SQL', 'Python', 'Tableau', '统计学'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: -1 },
    icon: '📊',
    description: '通过对业务数据的分析，发现增长机会、评估策略效果、支撑业务决策。是连接"数据"和"业务"的桥梁角色。',
    personality: '需要强大的逻辑思维(T型)和落地执行能力(S型)。J型在规划分析框架和交付报告时有优势。这个岗位介于技术和业务之间。',
    dayInLife: '10:00 查看数据看板/异常监控 → 11:00 取数需求处理 → 14:00 专项分析报告 → 16:30 与业务方沟通需求 → 18:00 数据复盘会议',
    companies: '字节跳动、腾讯、阿里巴巴、美团、滴滴、快手、京东',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习 Excel 高级功能(透视表/函数)', '学习基础统计学(描述统计/概率)', '阅读《用数据讲故事》', '养成用数据记录生活的习惯'] },
      sophomore: { title: '大二·基础期', items: ['系统学习 SQL(MySQL/PostgreSQL)', '学习 Python(Pandas/NumPy)', '学习 Tableau/FineBI 可视化', '参加数学建模比赛'] },
      junior: { title: '大三·实战期', items: ['深入学习 A/B测试、因果推断', '学习机器学习基础(分类/聚类)', 'Kaggle 打比赛攒项目经验', '找一份数据分析实习'] },
      senior: { title: '大四·冲刺期', items: ['整理分析项目作品集', '刷 SQL+Python+统计 面试题', '秋招投递(互联网/金融/咨询)', '考虑是否读研深造(统计学/数据科学)'] },
    },
    skills: [
      { name: 'SQL', type: 'required', desc: '复杂查询、窗口函数、性能优化' },
      { name: 'Python (Pandas/NumPy)', type: 'required', desc: '数据处理与统计分析' },
      { name: '统计学基础', type: 'required', desc: '假设检验、回归分析、概率论' },
      { name: 'Tableau/PowerBI', type: 'recommended', desc: '数据可视化与看板搭建' },
      { name: 'A/B测试', type: 'recommended', desc: '实验设计与分析' },
      { name: '机器学习基础', type: 'recommended', desc: '分类、聚类、预测模型' },
      { name: '业务理解能力', type: 'required', desc: '能把数据翻译成业务语言' },
      { name: 'Hive/Spark', type: 'advanced', desc: '大数据平台使用' },
    ],
  },
  {
    id: 'backend-dev',
    title: '后端开发工程师',
    industry: '互联网/科技',
    salary: '15-26K (应届)', salaryRange: '应届15-26K → 3年25-45K → 5年40-70K',
    tags: ['Java/Go', '数据库', '系统设计', 'Linux'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: -1 },
    icon: '⚙️',
    description: '负责服务端架构设计、API开发、数据库设计、系统性能优化。是互联网产品的"地基"，需要扎实的计算机基础。',
    personality: '适合逻辑思维强(T型)、能沉下心钻研(I型)的人。S型在关注系统稳定性和细节方面有天然优势。',
    dayInLife: '10:00 站会 → 10:30 写代码/设计方案 → 14:00 Code Review → 16:00 联调/性能优化 → 19:00 On-call值班/技术学习',
    companies: '字节跳动、阿里巴巴、腾讯、美团、华为、京东、网易',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习一门编程语言(Java/C++/Go)', '学习数据结构基础', '用学到的语言写一些小工具', '注册 LeetCode，开始刷简单题'] },
      sophomore: { title: '大二·基础期', items: ['深入学习计算机网络、操作系统', '学习数据库原理(MySQL)', '学习 Linux 基础操作', '跟着教程做一个完整项目'] },
      junior: { title: '大三·实战期', items: ['学习分布式系统基础', '学习 Redis、消息队列等中间件', '深入一个框架(Spring/Go-zero)', '找一份后端开发实习'] },
      senior: { title: '大四·冲刺期', items: ['刷 LeetCode (300+题)', '深入学习系统设计', '整理项目经验', '秋招海投+精准内推'] },
    },
    skills: [
      { name: 'Java 或 Go', type: 'required', desc: '精通至少一门后端语言' },
      { name: '数据结构与算法', type: 'required', desc: '面试重中之重' },
      { name: 'MySQL/Redis', type: 'required', desc: '数据库设计与优化' },
      { name: 'Linux', type: 'required', desc: '日常开发环境与部署' },
      { name: '计算机网络', type: 'recommended', desc: 'TCP/IP, HTTP协议' },
      { name: '消息队列(Kafka/RMQ)', type: 'recommended', desc: '异步处理与解耦' },
      { name: 'Docker/K8s', type: 'recommended', desc: '容器化与编排' },
      { name: '系统设计', type: 'advanced', desc: '高并发、高可用架构' },
    ],
  },
  {
    id: 'management-trainee',
    title: '管理培训生',
    industry: '快消/零售',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年18-30K → 5年25-50K',
    tags: ['轮岗培养', '领导力', '快速晋升', '综合能力'],
    matchProfile: { IE: 2, TF: -1, JP: 1, SN: 1 },
    icon: '🎯',
    description: '通过1-2年的轮岗机制，在市场营销、供应链、销售、财务等部门快速学习，目标是培养成为未来的管理者。',
    personality: '外向、善于沟通(E型)是基本要求。需要有较强的适应能力(P型偏灵活)和对商业的敏感度(N型)。',
    dayInLife: '09:00 部门早会 → 10:00 轮岗项目执行 → 14:00 培训课程/导师沟通 → 16:00 跨部门项目协调 → 18:00 管培生社群活动',
    companies: '宝洁、联合利华、玛氏、百威、欧莱雅、可口可乐、雀巢',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['加入学生会/社团，锻炼领导力', '参加商业案例比赛(P&G CEO Challenge)', '阅读商业类书籍和杂志', '学好英语(听说读写)'] },
      sophomore: { title: '大二·基础期', items: ['选修市场营销、组织行为学课程', '练习Case Interview(案例面试)', '参加快消/咨询公司的Open Day', '做一段有title的社团负责人'] },
      junior: { title: '大三·实战期', items: ['投递暑期实习(快消管培暑期项目)', '系统准备行为面试(STAR法则)', '建立LinkedIn职业形象', '参加商业分析实习'] },
      senior: { title: '大四·冲刺期', items: ['全力准备秋招管培项目', '群面模拟练习(无领导小组)', '跟进目标公司的招聘动态', '准备英语面试'] },
    },
    skills: [
      { name: '英语流利', type: 'required', desc: '大部分快消管培要求英语面试' },
      { name: '领导力经历', type: 'required', desc: '社团/项目/实习中的领导角色' },
      { name: '商业分析', type: 'recommended', desc: '能看懂P&L，做市场分析' },
      { name: 'Excel/PPT', type: 'required', desc: '数据分析与汇报展示' },
      { name: '跨部门沟通', type: 'recommended', desc: '能协调多方利益' },
      { name: '项目管理', type: 'recommended', desc: '能推进复杂项目落地' },
      { name: '数字化营销', type: 'advanced', desc: '社交媒体、电商运营' },
      { name: '财务基础', type: 'advanced', desc: '读懂财务报表' },
    ],
  },
  {
    id: 'consulting-analyst',
    title: '咨询顾问(分析师)',
    industry: '咨询/四大',
    salary: '14-24K (应届)', salaryRange: '应届14-24K → 3年25-45K → 5年45-80K → MBA后100K+',
    tags: ['商业分析', 'PPT', '逻辑思维', 'Case面试'],
    matchProfile: { IE: 1, TF: 2, JP: 1, SN: 1 },
    icon: '📈',
    description: '为企业客户提供战略、运营、组织等方向的咨询服务。通过结构化分析帮助客户解决问题，是商业世界的"医生"。',
    personality: '强大的逻辑分析能力(T型)是底线，同时需要优秀的沟通能力(E型)来与客户交互。J型在管理多项目时间线上有优势。',
    dayInLife: '09:00 团队晨会 → 10:00 客户访谈/调研 → 14:00 数据分析/建模 → 17:00 PPT报告撰写 → 20:00 内部评审 → 22:00 修改交付物',
    companies: '麦肯锡、BCG、贝恩、德勤、普华永道、安永、毕马威、罗兰贝格',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['保持GPA 3.7+ (咨询极为看重成绩)', '阅读《Case in Point》了解案例面试', '加入咨询社团或商业类组织', '练习英语口语和书面表达'] },
      sophomore: { title: '大二·基础期', items: ['系统练习Case Interview(30+个案例)', '学习结构化思维和MECE原则', '参加咨询公司的低年级项目', '做一份PTA(兼职助理)实习'] },
      junior: { title: '大三·实战期', items: ['冲刺MBB/Tier2的暑期实习', '持续提升Case能力(做到50+案例)', '掌握基本财务模型和数据分析', '保持高GPA + 有亮点的简历'] },
      senior: { title: '大四·冲刺期', items: ['全力冲刺秋招(咨询公司名额很少)', '模拟面试(行为面+Case面)', '如果未上岸，考虑读研/MBA迂回', '或先入行再内部转咨询'] },
    },
    skills: [
      { name: '结构化思维', type: 'required', desc: 'MECE、逻辑树、假设驱动' },
      { name: 'Case Interview', type: 'required', desc: 'Market Sizing, Profitability等' },
      { name: 'PPT/Excel', type: 'required', desc: '制作专业级交付物' },
      { name: '英语流利', type: 'required', desc: '全英文面试和工作环境' },
      { name: '财务建模', type: 'recommended', desc: 'DCF、三张表分析' },
      { name: '高GPA + 名校', type: 'required', desc: '咨询行业的入场券' },
      { name: '行业专长', type: 'advanced', desc: '深耕某个行业(医药/科技/金融)' },
      { name: '领导力经历', type: 'recommended', desc: '社团、竞赛、创业等' },
    ],
  },
  {
    id: 'civil-service',
    title: '公务员/事业编',
    industry: '公务员/事业编',
    salary: '8-15K (视城市)', salaryRange: '起薪一般 → 但含公积金+福利+稳定性溢价',
    tags: ['行测', '申论', '体制内', '稳定'],
    matchProfile: { IE: 0, TF: 1, JP: 2, SN: -1 },
    icon: '🏛️',
    description: '通过国考/省考进入政府机关或事业单位。工作稳定，福利完善，在不确定的时代提供确定性。',
    personality: 'J型(规划型)在备考和日常工作中极为重要，S型(务实型)在政策执行上有优势。能接受重复性工作和较长反馈周期。',
    dayInLife: '09:00 处理文件/公文 → 10:30 部门会议 → 14:00 调研/撰写报告 → 16:30 接待群众/企业 → 18:00 整理归档',
    companies: '中央部委、地方公务员、税务/海关/公安系统、事业单位(教师/医生/科研)',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['了解国考/省考/选调生的区别', '保持成绩，争取入党', '锻炼公文写作能力', '关注时事政治(FM/新闻联播)'] },
      sophomore: { title: '大二·基础期', items: ['开始刷行测题目(粉笔/中公)', '学习申论写作框架', '竞选学生干部或参加社会实践', '确定目标省份和岗位类型'] },
      junior: { title: '大三·实战期', items: ['系统刷行测(每天2小时+)', '每周写2-3篇申论', '关注选调生和人才引进政策', '参加体制内实习(政府见习)'] },
      senior: { title: '大四·冲刺期', items: ['全力冲刺国考(11月)和省考(次年3月)', '同时投递人才引进和选调生', '面试模拟(结构化面试)', '如果未上岸，准备事业单位/国企备选'] },
    },
    skills: [
      { name: '行测', type: 'required', desc: '言语、数量、判断、资料分析' },
      { name: '申论', type: 'required', desc: '归纳概括、综合分析、大作文' },
      { name: '政治素养', type: 'required', desc: '时政、党史、政策法规' },
      { name: '结构化面试', type: 'required', desc: '综合分析、组织管理、应急应变' },
      { name: '公文写作', type: 'recommended', desc: '通知、报告、函、纪要' },
      { name: 'Office技能', type: 'recommended', desc: 'Word排版、Excel统计' },
      { name: '法律基础', type: 'recommended', desc: '宪法、行政法基础' },
      { name: '群众工作能力', type: 'advanced', desc: '基层工作经验积累' },
    ],
  },
  {
    id: 'investment-analyst',
    title: '行业研究员/投资分析师',
    industry: '金融/投资',
    salary: '15-30K (应届)', salaryRange: '应届15-30K → 3年25-50K → 5年40-100K+',
    tags: ['财务分析', '行业研究', '估值建模', 'CFA/CPA'],
    matchProfile: { IE: -1, TF: 2, JP: 2, SN: 1 },
    icon: '💰',
    description: '深入分析行业趋势和公司基本面，为投资决策提供研究支持。需要对数字敏感、有好奇心、能承受高强度工作。',
    personality: 'T型(理性分析)是核心能力，J型(规划)在覆盖多行业和写报告时间管理上很重要。N型(创新思维)帮助发现被低估的投资机会。',
    dayInLife: '08:00 晨会/早报阅读 → 09:30 上市公司调研/电话会 → 13:00 财务模型更新 → 15:00 撰写研究报告 → 18:00 内部评审 → 21:00 继续写报告',
    companies: '中金、中信、华泰、易方达、华夏基金、高毅资产、红杉、高瓴',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习基础会计学(读懂三张表)', '关注财经新闻(FT/WSJ/财新)', '学习Excel高级功能', '了解金融行业基本结构'] },
      sophomore: { title: '大二·基础期', items: ['学习公司金融和估值方法', '学习财务建模(DCF/可比公司)', '准备CFA Level 1', '找一份券商/基金小黑工实习'] },
      junior: { title: '大三·实战期', items: ['通过CFA L1，准备L2', '深度覆盖1-2个行业,产出研究报告', '冲刺暑期实习(研究所/基金/PE)', '建立金融圈人脉(校友/领英)'] },
      senior: { title: '大四·冲刺期', items: ['秋招冲刺(研究所/基金/资管)', '持续更新行业研究观点', '如果没有直接上岸,先做卖方再跳买方', '读研可以大幅提升竞争力(985/海外)'] },
    },
    skills: [
      { name: '财务分析', type: 'required', desc: '三张表、比率分析、盈利预测' },
      { name: '估值建模', type: 'required', desc: 'DCF、可比公司、先例交易' },
      { name: '行业研究', type: 'required', desc: '产业链、竞争格局、政策分析' },
      { name: 'Excel高级', type: 'required', desc: '建模、数据透视、宏' },
      { name: '金融终端(Wind/Bloomberg)', type: 'recommended', desc: '数据获取与分析' },
      { name: 'CFA/CPA', type: 'recommended', desc: '行业的通行证' },
      { name: 'PPT/Presentation', type: 'recommended', desc: '研究报告与路演展示' },
      { name: 'Python/SQL', type: 'advanced', desc: '量化分析与数据处理' },
    ],
  },
  {
    id: 'hr-specialist',
    title: '人力资源(HR)',
    industry: '全行业',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年15-30K → 5年25-50K',
    tags: ['招聘', '员工关系', '组织发展', '沟通协调'],
    matchProfile: { IE: 2, TF: -2, JP: 1, SN: -1 },
    icon: '🤝',
    description: '负责企业的人才招聘、培训发展、薪酬福利、员工关系等工作。是连接公司和员工的桥梁，需要高情商和对人的理解力。',
    personality: 'F型(感性)在理解员工诉求和共情上有天然优势，E型(外向)在招聘和员工沟通中如鱼得水。需要同时兼顾公司利益和个人关怀。',
    dayInLife: '09:30 筛选简历 → 11:00 面试候选人 → 14:00 员工入职/离职办理 → 16:00 HR项目推进 → 18:00 员工关系沟通/团建策划',
    companies: '几乎所有公司都有HR需求。大厂HR(字节/阿里/腾讯)薪资更高，外企HR体系更成熟。',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习基础心理学/组织行为学', '加入学生会人力资源部锻炼', '阅读HR相关书籍', '观察不同组织的管理方式'] },
      sophomore: { title: '大二·基础期', items: ['学习劳动法/劳动合同法基础', '练习沟通和面试技巧', '考取人力资源管理师(四级)', '做校园大使/校园猎头积累经验'] },
      junior: { title: '大三·实战期', items: ['学习薪酬设计/绩效管理', '找一份HR实习(招聘或HRBP方向)', '系统学习组织发展(OD)方法论', '熟悉主流HR系统(PeopleSoft等)'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递各行业HR岗', '准备行为面试/情景模拟', '如果可能，争取管培轮岗到HR方向', '考取人力资源管理师(三级)'] },
    },
    skills: [
      { name: '沟通与共情', type: 'required', desc: '理解诉求,化解冲突' },
      { name: '劳动法知识', type: 'required', desc: '合规用工基础' },
      { name: '招聘全流程', type: 'required', desc: '从JD到offer' },
      { name: 'Excel/数据分析', type: 'recommended', desc: '人力成本分析与报表' },
      { name: '心理学基础', type: 'recommended', desc: '理解人的行为动机' },
      { name: '组织发展(OD)', type: 'advanced', desc: '组织诊断与变革' },
      { name: '薪酬绩效设计', type: 'advanced', desc: '激励体系搭建' },
      { name: 'HRIS系统', type: 'recommended', desc: '数字化人力管理' },
    ],
  },
  {
    id: 'marketing-brand',
    title: '品牌/市场营销',
    industry: '快消/零售',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年18-30K → 5年30-55K',
    tags: ['品牌策划', '消费者洞察', '数字营销', '项目管理'],
    matchProfile: { IE: 1, TF: -1, JP: 0, SN: 2 },
    icon: '📣',
    description: '负责品牌定位、营销活动策划、消费者洞察分析、线上线下推广策略。需要创造力+数据思维的双重能力。',
    personality: 'N型(创新思维)是核心——你需要想出别人没想到的创意。F型(感性)帮助你理解消费者的情感诉求。E型帮助跨部门推动营销项目。',
    dayInLife: '10:00 查看营销数据看板 → 11:00 创意脑暴会 → 14:00 供应商沟通(广告公司/KOL) → 16:00 活动方案撰写 → 18:00 竞品分析',
    companies: '宝洁、欧莱雅、可口可乐、Nike、LVMH、完美日记、花西子、瑞幸',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['阅读营销经典(定位/疯传/影响力)', '运营一个自己的社交媒体账号', '学习基础设计软件(PS/Canva)', '关注喜欢的品牌,分析它们的营销套路'] },
      sophomore: { title: '大二·基础期', items: ['学习市场调研方法', '学习数字营销(SEO/信息流/短视频)', '参加商赛(欧莱雅Brandstorm等)', '做一份市场营销实习'] },
      junior: { title: '大三·实战期', items: ['深入学习消费者行为学', '独立策划并执行一次完整Campaign', '学习抖音/小红书/TikTok运营', '冲刺快消公司暑期实习'] },
      senior: { title: '大四·冲刺期', items: ['整理营销作品集(Campaign案例)', '秋招投递(快消/互联网市场部)', '关注新消费品牌机会', '持续关注营销趋势(AI营销/直播电商)'] },
    },
    skills: [
      { name: '消费者洞察', type: 'required', desc: '理解消费者需求与行为' },
      { name: '品牌策划', type: 'required', desc: '定位、调性、Campaign设计' },
      { name: '数字营销', type: 'recommended', desc: '抖音、小红书、微信生态' },
      { name: '数据分析', type: 'recommended', desc: 'ROI分析、用户画像' },
      { name: '内容创作', type: 'required', desc: '文案、短视频、视觉' },
      { name: '项目管理', type: 'recommended', desc: '多线程推进Campaign' },
      { name: '英语', type: 'recommended', desc: '外企营销部标配' },
      { name: 'AI营销工具', type: 'advanced', desc: 'Midjourney、AI文案、数字人' },
    ],
  },
  {
    id: 'ai-engineer',
    title: 'AI/算法工程师',
    industry: '互联网/科技',
    salary: '20-35K (应届)', salaryRange: '应届20-35K → 3年35-60K → 5年60-120K+ (含股票)',
    tags: ['机器学习', '深度学习', 'Python', 'NLP/CV'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: 2 },
    icon: '🤖',
    description: '研究和应用AI算法解决实际问题，包括推荐系统、自然语言处理、计算机视觉等方向。是当前薪资最高、竞争最激烈的技术岗位之一。',
    personality: 'N型(创新思维)和T型(逻辑分析)是双核驱动。I型(J型)适合长时间的模型训练和论文阅读。要有持续学习的能力——这个领域半年不学就落后。',
    dayInLife: '10:00 看最新论文/技术动态 → 11:00 模型训练/调参 → 14:00 与工程团队对接模型部署 → 16:00 实验数据分析 → 19:00 技术分享/继续看论文',
    companies: '字节跳动(推荐)、腾讯(AI Lab)、阿里(达摩院)、商汤、旷视、百度、华为',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学好数学(线性代数/概率论/微积分)', '学习 Python 编程', '学习吴恩达机器学习课程(Coursera)', '阅读科普级AI读物培养兴趣'] },
      sophomore: { title: '大二·基础期', items: ['深入学习机器学习理论', '学习深度学习框架(PyTorch)', '学习传统ML模型(树模型/SVM/聚类)', 'Kaggle打比赛(争取拿牌)'] },
      junior: { title: '大三·实战期', items: ['确定方向(NLP/CV/推荐/RL选一个)', '复现顶会论文(ICLR/NeurIPS/CVPR)', '争取发一篇论文', '找AI相关实习(日常/暑期)'] },
      senior: { title: '大四·冲刺期', items: ['最好读研/AI方向硕士', '如果不读,秋招冲刺算法岗(竞争极激烈)', '整理论文/比赛/项目成果', '持续跟进前沿技术(大模型等)'] },
    },
    skills: [
      { name: 'Python + PyTorch', type: 'required', desc: '核心开发工具' },
      { name: '机器学习理论', type: 'required', desc: '模型原理与数学推导' },
      { name: '深度学习', type: 'required', desc: 'CNN/RNN/Transformer等' },
      { name: '数学基础', type: 'required', desc: '线代/概率/优化理论' },
      { name: '论文阅读能力', type: 'required', desc: '跟进顶会最新成果' },
      { name: '工程能力', type: 'recommended', desc: '模型部署/性能优化' },
      { name: '数据处理', type: 'recommended', desc: '数据清洗/特征工程' },
      { name: '大模型/LLM', type: 'advanced', desc: 'Prompt工程/微调/RAG' },
    ],
  },
  {
    id: 'product-operations',
    title: '产品运营',
    industry: '互联网/科技',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年15-28K → 5年25-45K',
    tags: ['用户运营', '活动策划', '数据分析', '内容运营'],
    matchProfile: { IE: 1, TF: 0, JP: 1, SN: 0 },
    icon: '🎪',
    description: '负责产品的用户增长、活跃、留存等核心指标。通过活动策划、用户触达、内容运营等手段让产品"活起来"。',
    personality: '综合性很强：既需要E型的沟通推进，也需要S型的执行落地，F型在理解用户情感上很有帮助。',
    dayInLife: '10:00 看数据看板/异常排查 → 11:00 用户反馈处理 → 14:00 活动策划/执行 → 16:00 跨部门协作(产品/市场) → 18:00 活动复盘',
    companies: '字节跳动、腾讯、美团、小红书、B站、快手、滴滴',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习Excel数据分析', '参与一个社团或活动的组织', '运营一个自己感兴趣的小社群', '阅读《增长黑客》《上瘾》'] },
      sophomore: { title: '大二·基础期', items: ['学习SQL基础查询', '学习用户运营方法论(RFM模型等)', '深度参与1-2个校园项目运营', '找一份运营实习(内容/用户方向)'] },
      junior: { title: '大三·实战期', items: ['学习A/B测试和实验设计', '独立负责一个运营项目', '深入学习增长方法论', '冲刺互联网公司暑期实习'] },
      senior: { title: '大四·冲刺期', items: ['整理运营案例作品集', '秋招投递互联网运营岗', '面试准备(运营sense + 数据分析)', '关注各细分运营方向(策略/增长/内容)'] },
    },
    skills: [
      { name: '数据分析(SQL/Excel)', type: 'required', desc: '数据驱动运营决策' },
      { name: '活动策划', type: 'required', desc: '从方案到执行到复盘' },
      { name: '用户理解', type: 'required', desc: '用户分群、画像、触达' },
      { name: '内容能力', type: 'recommended', desc: '文案、短视频、社区运营' },
      { name: '增长方法论', type: 'recommended', desc: '拉新、促活、留存策略' },
      { name: '项目管理', type: 'recommended', desc: '跨部门资源协调' },
      { name: 'Python基础', type: 'advanced', desc: '自动化运营工具' },
      { name: '私域运营', type: 'advanced', desc: '企微/社群/会员体系' },
    ],
  },
  {
    id: 'game-planner',
    title: '游戏策划',
    industry: '游戏/娱乐',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年18-30K → 5年30-60K (含项目奖金)',
    tags: ['系统设计', '数值策划', '关卡设计', '游戏理解'],
    matchProfile: { IE: -1, TF: 1, JP: 0, SN: 2 },
    icon: '🎮',
    description: '设计游戏的核心玩法、数值体系、关卡内容和用户体验。是最有"造物主"感的岗位，但也需要极强的逻辑和数据分析能力。',
    personality: 'N型(创新)是最重要的——你要创造别人没玩过的东西。T型(逻辑)保证数值平衡和系统严谨。I型(J型)能接受长时间的设计打磨。',
    dayInLife: '10:30 体验竞品游戏 → 13:00 设计文档撰写 → 15:00 与程序/美术沟通需求 → 17:00 版本体验/反馈收集 → 19:00 数值调试/平衡调整',
    companies: '腾讯游戏、网易游戏、米哈游、莉莉丝、鹰角、叠纸、FunPlus',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['深度玩10款以上不同类型游戏', '学习写游戏评测/拆解文档', '了解游戏开发基本流程', '尝试用游戏引擎(Godot/Unity)做小Demo'] },
      sophomore: { title: '大二·基础期', items: ['系统学习游戏策划方法论', '学习Excel高级(数值建模)', '拆解经典游戏的设计原理', '参加Game Jam(48小时做游戏)'] },
      junior: { title: '大三·实战期', items: ['独立完成一个可玩的游戏Demo', '深入了解数值设计/经济系统', '找一份游戏公司实习', '关注游戏行业动态(GameLook等)'] },
      senior: { title: '大四·冲刺期', items: ['整理游戏作品集(最重要)', '秋招投递游戏公司策划岗', '笔试准备(数值题/设计题)', '如果进不了大厂,先入行中小团队积累经验'] },
    },
    skills: [
      { name: '游戏理解力', type: 'required', desc: '深度玩家思维+设计者视角' },
      { name: '数值设计', type: 'required', desc: 'Excel建模、经济系统平衡' },
      { name: '系统设计文档', type: 'required', desc: '清晰完整的设计表达' },
      { name: '沟通协调', type: 'required', desc: '与程序/美术高效协作' },
      { name: 'Unity/UE基础', type: 'recommended', desc: '理解技术实现边界' },
      { name: '概率与统计', type: 'recommended', desc: '抽卡/掉落等数值设计' },
      { name: '用户心理学', type: 'advanced', desc: '付费心理、心流设计' },
      { name: '数据分析(SQL)', type: 'advanced', desc: '版本数据分析调优' },
    ],
  },
  {
    id: 'new-media',
    title: '新媒体运营/内容创作',
    industry: '广告/传媒',
    salary: '8-15K (应届)', salaryRange: '应届8-15K → 3年15-25K → 5年25-45K (头部自媒体更高)',
    tags: ['内容创作', '短视频', '社交媒体', '用户增长'],
    matchProfile: { IE: 1, TF: -2, JP: -1, SN: 2 },
    icon: '✨',
    description: '负责自媒体账号的内容策划、创作和运营。需要对热点敏感、善于用内容打动人心、理解平台算法逻辑。',
    personality: 'N型(创意)和F型(感性)是关键——好的内容需要创意和共情。P型(灵活)让你能快速响应热点变化。',
    dayInLife: '10:00 刷热点/找选题 → 11:00 写脚本/文案 → 14:00 拍摄/剪辑 → 17:00 发布+数据监控 → 20:00 与粉丝互动/分析数据 → 随时追热点',
    companies: '互联网大厂内容部、MCN机构(无忧传媒等)、自媒体创业、传统媒体新媒体部',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['选定一个平台深耕(抖音/B站/小红书)', '学习基础拍摄和剪辑(剪映/PR)', '研究100个爆款内容的特点', '发布第一个作品,不怕数据差'] },
      sophomore: { title: '大二·基础期', items: ['坚持内容输出(周更至少2条)', '学习脚本写作和叙事结构', '学习基础PS/AE', '分析后台数据,优化内容方向'] },
      junior: { title: '大三·实战期', items: ['做到1000+粉丝(任一平台)', '学习短视频运营和投放(Dou+)', '找一份新媒体实习', '建立内容创作的SOP化流程'] },
      senior: { title: '大四·冲刺期', items: ['整理作品集和账号数据', '投递互联网内容运营/MCN编导', '或继续做大自己的账号', '关注AI内容创作工具'] },
    },
    skills: [
      { name: '内容策划', type: 'required', desc: '选题、脚本、文案能力' },
      { name: '视频剪辑', type: 'required', desc: '剪映/PR/FCP' },
      { name: '平台算法理解', type: 'required', desc: '抖音/B站/小红书推荐机制' },
      { name: '热点敏感度', type: 'required', desc: '快速响应热点的能力' },
      { name: '数据分析', type: 'recommended', desc: '播放量/转化率/粉丝画像分析' },
      { name: 'PS/设计基础', type: 'recommended', desc: '封面图/海报制作' },
      { name: '直播运营', type: 'advanced', desc: '带货/知识付费直播' },
      { name: '商业变现', type: 'advanced', desc: '广告/电商/知识付费模式' },
    ],
  },
  {
    id: 'supply-chain',
    title: '供应链管理',
    industry: '制造业',
    salary: '10-16K (应届)', salaryRange: '应届10-16K → 3年15-25K → 5年25-45K',
    tags: ['物流规划', '采购', '库存管理', 'ERP系统'],
    matchProfile: { IE: -1, TF: 1, JP: 2, SN: -1 },
    icon: '🔗',
    description: '负责企业供应链的设计、优化和管理，包括采购、生产计划、物流配送、库存控制等。是制造业和零售业的核心岗位。',
    personality: 'J型(规划型)在这个岗位上有极大优势——供应链就是要提前规划、精确执行。S型(务实)关注具体的流程和效率改进。',
    dayInLife: '09:00 查看库存和订单状态 → 10:30 供应商沟通/谈判 → 14:00 数据分析/需求预测 → 16:00 仓储/物流现场管理 → 17:30 系统流程优化',
    companies: '华为、大疆、比亚迪、特斯拉、京东物流、顺丰、美的、海尔',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习供应链基础概念(SCOR模型等)', '学习Excel高级应用', '了解ERP系统基本功能', '关注制造业新闻(36氪/亿欧)'] },
      sophomore: { title: '大二·基础期', items: ['学习运筹学和优化理论', '学习SQL基础', '参加供应链相关比赛', '了解精益生产和六西格玛'] },
      junior: { title: '大三·实战期', items: ['深入学习ERP系统(SAP/Oracle)', '学习库存管理和需求预测', '找一份供应链/物流实习', '考取CPIM/CSCP等认证'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递制造/零售/物流公司', '面试准备(案例分析+数据分析)', '如果可能，争取管培轮岗到供应链方向', '关注智能制造和数字化供应链趋势'] },
    },
    skills: [
      { name: 'Excel/数据分析', type: 'required', desc: '需求预测、库存分析' },
      { name: 'ERP系统', type: 'required', desc: 'SAP / Oracle / 用友' },
      { name: '运筹学基础', type: 'recommended', desc: '优化算法、线性规划' },
      { name: '供应链理论', type: 'required', desc: 'SCOR模型、精益生产' },
      { name: '项目管理', type: 'recommended', desc: '端到端流程优化' },
      { name: 'SQL', type: 'recommended', desc: '供应链数据查询分析' },
      { name: 'CPIM/CSCP', type: 'advanced', desc: '国际供应链认证' },
      { name: 'Python自动化', type: 'advanced', desc: '供应链报表自动化' },
    ],
  },
  // ═══ 第二批岗位 (16-35) ═══
  {
    id: 'ux-ui-designer',
    title: 'UX/UI设计师',
    industry: '互联网/科技',
    salary: '12-22K (应届)', salaryRange: '应届12-22K → 3年20-35K → 5年30-55K',
    tags: ['交互设计', '视觉设计', 'Figma', '用户研究'],
    matchProfile: { IE: 0, TF: -1, JP: 0, SN: 2 },
    icon: '🎨',
    description: '负责产品界面设计和用户体验优化。从用户研究出发，通过交互设计和视觉设计，打造好看、好用、让用户"上瘾"的产品体验。',
    personality: 'N型(创新)让你能想出让人惊喜的交互方案，F型(感性)帮你理解用户的情感体验。需要审美+逻辑的双重能力。',
    dayInLife: '10:00 设计评审 → 11:00 交互原型设计(Figma) → 14:00 用户访谈/可用性测试 → 16:00 视觉稿输出 → 18:00 Dribbble/Behance 作品打磨',
    companies: '字节跳动、腾讯、阿里巴巴、美团、百度、网易、快手、小红书、大疆',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习设计基础(平面构成/色彩/排版)', '临摹100个优秀APP界面', '学习Figma/Sketch', '建立Dribbble/站酷账号'] },
      sophomore: { title: '大二·基础期', items: ['系统学习交互设计原则', '学习用户研究方法论', '掌握设计系统(Design System)', '参加设计比赛/做虚拟项目'] },
      junior: { title: '大三·实战期', items: ['独立完成2-3个完整的UX/UI作品', '学习动效设计(Principle/AE)', '找一份设计实习', '建立作品集网站'] },
      senior: { title: '大四·冲刺期', items: ['完善作品集(5+完整项目)', '秋招投递互联网设计岗', '准备作品集讲解和设计挑战面试', '持续关注设计趋势(AI设计/VR/AR)'] },
    },
    skills: [
      { name: 'Figma/Sketch', type: 'required', desc: '核心设计工具' },
      { name: '交互设计', type: 'required', desc: '信息架构、流程设计、原型' },
      { name: '视觉设计', type: 'required', desc: '排版、配色、图标、插画' },
      { name: '设计系统', type: 'required', desc: '组件化设计思维' },
      { name: '用户研究', type: 'recommended', desc: '访谈、问卷、可用性测试' },
      { name: '动效设计', type: 'recommended', desc: 'Principle/After Effects' },
      { name: 'HTML/CSS基础', type: 'recommended', desc: '理解开发实现边界' },
      { name: '3D/品牌设计', type: 'advanced', desc: 'C4D、品牌识别系统' },
    ],
  },
  {
    id: 'sre-devops',
    title: 'SRE/DevOps工程师',
    industry: '互联网/科技',
    salary: '16-28K (应届)', salaryRange: '应届16-28K → 3年28-50K → 5年45-80K',
    tags: ['Linux', 'Kubernetes', 'CI/CD', '监控告警'],
    matchProfile: { IE: -1, TF: 2, JP: 2, SN: -1 },
    icon: '🛡️',
    description: '负责系统的可靠性、可扩展性和运维自动化。确保线上服务"永不宕机"，同时提升研发效率和部署速度。',
    personality: '极强的T型(逻辑)和J型(规划)——你需要预判故障、制定预案、精确执行。S型有助于关注系统的每一个细节。',
    dayInLife: '09:00 巡检/On-call交接 → 10:30 自动化工具开发 → 14:00 容量规划/压测 → 16:00 CI/CD流水线优化 → 18:00 故障复盘/文档沉淀',
    companies: '字节跳动、阿里巴巴、腾讯、Google、AWS、华为、美团、滴滴',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习Linux基础命令和shell脚本', '了解计算机网络(TCP/IP, DNS, HTTP)', '搭建个人服务器(VPS/云主机)', '学习Git版本控制'] },
      sophomore: { title: '大二·基础期', items: ['深入Linux系统管理', '学习Docker容器技术', '学习一门脚本语言(Python/Go)', '了解CI/CD概念(Jenkins/GitLab CI)'] },
      junior: { title: '大三·实战期', items: ['学习Kubernetes编排', '学习监控体系(Prometheus/Grafana)', '学习基础设施即代码(Terraform)', '找一份运维/DevOps实习'] },
      senior: { title: '大四·冲刺期', items: ['考取CKA/CKAD认证', '深入学习分布式系统和容灾', '刷算法题(大厂SRE也考)', '秋招投递SRE/DevOps/平台工程岗'] },
    },
    skills: [
      { name: 'Linux系统管理', type: 'required', desc: '日常操作、性能调优、安全加固' },
      { name: 'Docker/Kubernetes', type: 'required', desc: '容器编排与集群管理' },
      { name: 'CI/CD流水线', type: 'required', desc: 'Jenkins/GitLab CI/GitHub Actions' },
      { name: '脚本编程(Python/Go/Shell)', type: 'required', desc: '自动化工具开发' },
      { name: '监控体系', type: 'recommended', desc: 'Prometheus/Grafana/ELK' },
      { name: 'Terraform/Ansible', type: 'recommended', desc: '基础设施即代码' },
      { name: '云平台(AWS/阿里云)', type: 'recommended', desc: '云原生架构' },
      { name: '混沌工程', type: 'advanced', desc: '故障演练与韧性测试' },
    ],
  },
  {
    id: 'security-engineer',
    title: '网络安全工程师',
    industry: '互联网/科技',
    salary: '14-26K (应届)', salaryRange: '应届14-26K → 3年25-50K → 5年40-80K',
    tags: ['渗透测试', '安全架构', '加密算法', '应急响应'],
    matchProfile: { IE: -1, TF: 2, JP: 2, SN: 2 },
    icon: '🔐',
    description: '保护企业的信息系统和用户数据安全。包括安全攻防、漏洞挖掘、安全架构设计、合规审计等方向。',
    personality: 'N型(创新)帮你从攻击者角度思考，T型(逻辑)保证安全方案的严密性。I型适合长时间的漏洞挖掘和代码审计。',
    dayInLife: '09:30 安全态势感知 → 11:00 漏洞复现/渗透测试 → 14:00 代码审计/安全评审 → 16:00 安全工具开发 → 18:30 CTF训练/安全研究',
    companies: '奇安信、深信服、绿盟、360、华为、阿里巴巴、腾讯安全、字节安全',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习计算机网络(TCP/IP协议栈)', '学习Linux系统基础', '了解常见Web漏洞(OWASP Top 10)', '注册漏洞盒子/补天平台'] },
      sophomore: { title: '大二·基础期', items: ['深入学习Web安全(SQL注入/XSS/CSRF)', '学习Python编写安全工具', '学习密码学基础', '参加CTF比赛(从入门级开始)'] },
      junior: { title: '大三·实战期', items: ['学习二进制安全/逆向工程', '挖掘SRC漏洞(补天/漏洞盒子)', '学习内网渗透和域安全', '找一份安全实习'] },
      senior: { title: '大四·冲刺期', items: ['考取CISP/CISSP/CISA等认证', '持续SRC漏洞挖掘', '秋招投递安全岗', '或读研深造(网安/密码学方向)'] },
    },
    skills: [
      { name: 'Web安全', type: 'required', desc: 'OWASP Top 10, 漏洞原理与利用' },
      { name: '渗透测试', type: 'required', desc: '信息收集、漏洞利用、后渗透' },
      { name: 'Python', type: 'required', desc: '编写POC/EXP和安全工具' },
      { name: '网络协议', type: 'required', desc: 'TCP/IP, HTTP, DNS深度理解' },
      { name: '代码审计', type: 'recommended', desc: 'Java/PHP/Node.js源码审计' },
      { name: '二进制安全', type: 'recommended', desc: '逆向工程、漏洞利用编写' },
      { name: '云安全', type: 'advanced', desc: 'AWS/阿里云安全体系' },
      { name: '威胁情报', type: 'advanced', desc: 'APT分析、取证溯源' },
    ],
  },
  {
    id: 'embedded-engineer',
    title: '嵌入式开发工程师',
    industry: '制造业',
    salary: '12-22K (应届)', salaryRange: '应届12-22K → 3年18-35K → 5年28-55K',
    tags: ['C/C++', 'RTOS', '单片机', 'Linux驱动'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: -1 },
    icon: '🔧',
    description: '负责嵌入式系统(智能硬件、汽车电子、工业控制等)的软件开发。写代码直接控制物理硬件，代码能"让物体动起来"。',
    personality: 'S型(务实落地)和T型(逻辑严密)是核心——嵌入式开发不能有任何"差不多"，bug可能导致物理损坏。I型适合长时间调试。',
    dayInLife: '09:00 看datasheet/规格书 → 10:30 写驱动/固件代码 → 14:00 硬件联调(示波器/逻辑分析仪) → 16:30 Bug调试 → 18:00 技术文档/测试报告',
    companies: '华为、大疆、比亚迪、小米、海康威视、汇顶科技、乐鑫、恩智浦、TI',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习C语言(指针/内存管理必须精通)', '学习电路基础(模电/数电)', '买一块开发板(STM32/ESP32)动手玩', '学习基本调试(串口/printf)'] },
      sophomore: { title: '大二·基础期', items: ['深入学习单片机(STM32 HAL库)', '学习RTOS(FreeRTOS/RT-Thread)', '学习通信协议(I2C/SPI/UART/CAN)', '做一个小项目(智能小车/温控器等)'] },
      junior: { title: '大三·实战期', items: ['学习嵌入式Linux(驱动/设备树)', '深入ARM架构', '学习实时系统和性能优化', '找一份嵌入式实习'] },
      senior: { title: '大四·冲刺期', items: ['深入一个行业方向(汽车电子/IoT/机器人)', '整理项目经验(GitHub + 文档)', '秋招投递(硬件大厂/汽车/芯片公司)', '关注RISC-V等新技术趋势'] },
    },
    skills: [
      { name: 'C语言', type: 'required', desc: '指针、内存管理、位运算精通' },
      { name: '单片机(STM32等)', type: 'required', desc: '外设驱动、中断、DMA' },
      { name: 'RTOS', type: 'required', desc: 'FreeRTOS/RT-Thread任务调度' },
      { name: '通信协议', type: 'required', desc: 'I2C/SPI/UART/CAN/USB' },
      { name: '嵌入式Linux', type: 'recommended', desc: '驱动开发、设备树、Buildroot' },
      { name: '硬件基础', type: 'recommended', desc: '看懂原理图、使用示波器' },
      { name: 'C++/Rust', type: 'recommended', desc: '现代嵌入式开发语言' },
      { name: '功能安全(MISRA/ISO26262)', type: 'advanced', desc: '车规级开发标准' },
    ],
  },
  {
    id: 'quantitative-analyst',
    title: '量化研究员',
    industry: '金融/投资',
    salary: '20-40K (应届)', salaryRange: '应届20-40K → 3年40-80K → 5年60-150K+ (含PnL分成)',
    tags: ['Python', '数学建模', '策略研发', '机器学习'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: 2 },
    icon: '📐',
    description: '用数学模型和计算机算法在金融市场中寻找交易机会。是脑力密集型岗位，需要极其扎实的数理基础和编程能力。',
    personality: 'N型(抽象思维)和T型(逻辑分析)必须双高。I型适合长时间的数据分析和策略打磨。这个岗位对数理天赋的要求是天花板级别的。',
    dayInLife: '08:30 晨会/市场回顾 → 09:30 策略回测/参数优化 → 13:00 数据分析/因子挖掘 → 15:00 实盘监控/风险检查 → 17:00 论文阅读/新思路研究 → 20:00 继续研究',
    companies: '幻方、九坤、明汯、衍复、佳期、WorldQuant、Jump Trading、Optiver',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['数学分析/高等代数/概率论必须90+', '学习Python(NumPy/Pandas)', '了解金融市场基础', '阅读量化入门书籍(打开量化投资的黑箱)'] },
      sophomore: { title: '大二·基础期', items: ['学习随机过程/时间序列分析', '学习机器学习基础', '在聚宽/米筐上写第一个策略', '学习C++(低延迟交易需要)'] },
      junior: { title: '大三·实战期', items: ['深入学习统计套利/多因子模型', '系统回测并优化策略', '参加量化比赛(WorldQuant/九坤)', '找一份量化实习(日常/暑期)'] },
      senior: { title: '大四·冲刺期', items: ['强烈建议读研(金融工程/数学/统计)', '如果不读,秋招冲刺量化私募/券商金工', '策略实盘小资金试验', '拿数学建模/MCM等竞赛奖项'] },
    },
    skills: [
      { name: 'Python + Pandas', type: 'required', desc: '数据分析与策略回测' },
      { name: '数学/统计学', type: 'required', desc: '概率论、随机过程、时间序列' },
      { name: '机器学习', type: 'required', desc: '因子挖掘、预测模型' },
      { name: '金融市场知识', type: 'required', desc: '股票/期货/期权的定价和交易' },
      { name: 'C++', type: 'recommended', desc: '低延迟交易系统' },
      { name: '数据库(SQL/KDB+)', type: 'recommended', desc: '海量行情数据存储' },
      { name: '深度学习', type: 'advanced', desc: 'LSTM/Transformer在量化中的应用' },
      { name: '高频交易', type: 'advanced', desc: '市场微观结构、订单簿分析' },
    ],
  },
  {
    id: 'accountant-auditor',
    title: '审计师',
    industry: '咨询/四大',
    salary: '10-16K (应届)', salaryRange: '应届10-16K → 3年18-30K → 5年30-55K (CPA签字后大幅提升)',
    tags: ['财务报表', '审计流程', 'CPA', 'Excel'],
    matchProfile: { IE: 0, TF: 2, JP: 2, SN: -1 },
    icon: '📋',
    description: '审查企业的财务报表，确保数据真实合规。四大的审计师是财经界的"黄埔军校"，培养体系完善，出路广阔。',
    personality: 'T型(逻辑)和J型(规划)是基本盘——你需要按审计程序严格推进，对数字有天然的敏感性。S型帮助发现细小的异常。',
    dayInLife: '09:00 客户现场/盘点 → 10:30 底稿编制 → 13:00 抽样测试 → 15:00 与客户沟通/索要资料 → 17:00 底稿Review → 忙季加班到深夜是常态',
    companies: '普华永道、德勤、安永、毕马威(四大) + 内资所(立信/天健/信永中和)',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习基础会计学(会计恒等式/借贷)', '学习Excel(数据透视/VLOOKUP)', '了解审计行业(四大vs内资)', '保持GPA(申请四大有门槛)'] },
      sophomore: { title: '大二·基础期', items: ['学习中级财务会计', '学习审计学基础', '开始备考CPA(会计/审计优先)', '参加四大Open Day/校园大使'] },
      junior: { title: '大三·实战期', items: ['通过CPA 2-3门', '学习税法/经济法', '申请四大寒假实习(年审忙季)', '如果拿到return offer就稳了'] },
      senior: { title: '大四·冲刺期', items: ['继续考完剩余CPA科目', '秋招冲刺四大审计岗', '准备群面(无领导小组)', '如果没进四大,先入内资所再跳'] },
    },
    skills: [
      { name: '会计准则', type: 'required', desc: 'CAS/IFRS/US GAAP' },
      { name: '审计方法论', type: 'required', desc: '风险评估、控制测试、实质性程序' },
      { name: 'Excel高级', type: 'required', desc: '数据透视、函数、VBA加分' },
      { name: 'CPA证书', type: 'required', desc: '审计职业的通行证' },
      { name: '沟通能力', type: 'recommended', desc: '与客户和团队高效协作' },
      { name: 'PPT报告', type: 'recommended', desc: '审计报告与管理建议书' },
      { name: '数据分析(ACL/IDEA)', type: 'recommended', desc: '审计数据分析工具' },
      { name: '英语流利', type: 'recommended', desc: '四大工作语言' },
    ],
  },
  {
    id: 'teacher',
    title: '教师/教育工作者',
    industry: '教育/培训',
    salary: '8-15K (应届)', salaryRange: '应届8-15K(公办有编制) + 寒暑假 + 稳定福利',
    tags: ['教学能力', '学科专业', '教师资格证', '耐心沟通'],
    matchProfile: { IE: 1, TF: -1, JP: 1, SN: -1 },
    icon: '📚',
    description: '在中小学或教育机构从事教学工作。公办教师有编制、稳定性极强；培训机构收入有弹性但压力更大。',
    personality: 'F型(感性)让你能理解学生的心理，E型(外向)在课堂上能感染学生。J型(计划)保证教学进度和效果。',
    dayInLife: '07:30 早读/备课 → 08:30-12:00 上课 → 14:00 批改作业/教研 → 16:30 课后辅导/社团活动 → 18:00 家长沟通/班主任事务',
    companies: '公立中小学(编制)、私立学校、新东方、好未来、高途、猿辅导、作业帮',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['确保学科专业知识扎实', '参加支教/家教积累教学经验', '考取普通话等级证书(二甲以上)', '了解各地教师编制政策'] },
      sophomore: { title: '大二·基础期', items: ['系统学习教育学/心理学', '练习板书和教学设计', '考教师资格证(笔试)', '参加教学技能比赛'] },
      junior: { title: '大三·实战期', items: ['完成教师资格证(面试)', '去中小学实习/支教一学期', '系统准备教师编制考试(教综+学科)', '关注目标城市的招聘公告'] },
      senior: { title: '大四·冲刺期', items: ['全力备考教师编制(多城市同时)', '同时投递私立学校和培训机构做备选', '面试模拟(试讲+结构化)', '如果不考编,考虑教育科技/在线教育公司'] },
    },
    skills: [
      { name: '教师资格证', type: 'required', desc: '入行必备' },
      { name: '学科专业知识', type: 'required', desc: '所教学科的深度掌握' },
      { name: '教学设计', type: 'required', desc: '教案编写、课堂组织' },
      { name: '普通话', type: 'required', desc: '二级甲等以上' },
      { name: '教育心理学', type: 'recommended', desc: '理解不同年龄段学生心理' },
      { name: '班级管理', type: 'recommended', desc: '班风建设、家校沟通' },
      { name: '教育技术', type: 'recommended', desc: '智慧课堂、在线教学工具' },
      { name: '学科竞赛辅导', type: 'advanced', desc: '奥赛/学科竞赛指导能力' },
    ],
  },
  {
    id: 'test-qa-engineer',
    title: '测试开发工程师',
    industry: '互联网/科技',
    salary: '12-22K (应届)', salaryRange: '应届12-22K → 3年20-35K → 5年30-50K',
    tags: ['自动化测试', 'Python/Java', '性能测试', '测试框架'],
    matchProfile: { IE: 0, TF: 2, JP: 1, SN: -1 },
    icon: '🧪',
    description: '保障软件产品质量，通过自动化测试、性能测试、安全测试等手段，确保产品上线前"万无一失"。是质量保障的最后一道防线。',
    personality: 'S型(关注细节)在这个岗位上极其重要——你需要想到别人想不到的边界情况。T型(逻辑)帮你设计严谨的测试用例。',
    dayInLife: '10:00 站会 → 10:30 编写自动化测试脚本 → 14:00 测试执行/Bug管理 → 16:00 CI/CD测试流水线维护 → 17:30 测试报告/质量复盘',
    companies: '字节跳动、阿里巴巴、腾讯、美团、百度、快手、网易、京东',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习Python或Java基础', '了解软件测试概念(白盒/黑盒)', '学习Linux基本操作', '阅读《软件测试的艺术》'] },
      sophomore: { title: '大二·基础期', items: ['深入学习自动化测试(Selenium/Appium)', '学习接口测试(Postman/Requests)', '学习SQL数据库操作', '跟着开源项目写测试用例'] },
      junior: { title: '大三·实战期', items: ['搭建自动化测试框架(Pytest/JUnit)', '学习性能测试(JMeter/Locust)', '学习CI/CD(Jenkins/GitHub Actions)', '找一份测试开发实习'] },
      senior: { title: '大四·冲刺期', items: ['深入学习测试架构', '刷算法题(大厂测开也考)', '整理测试项目经验', '秋招投递测开/质量工程岗'] },
    },
    skills: [
      { name: 'Python/Java', type: 'required', desc: '自动化测试脚本开发' },
      { name: '自动化测试框架', type: 'required', desc: 'Selenium/Appium/Pytest' },
      { name: 'SQL', type: 'required', desc: '数据验证与测试数据准备' },
      { name: '测试方法论', type: 'required', desc: '黑盒/白盒/边界值/等价类' },
      { name: '性能测试', type: 'recommended', desc: 'JMeter/Locust/Gatling' },
      { name: 'CI/CD', type: 'recommended', desc: 'Jenkins流水线配置' },
      { name: '安全测试', type: 'advanced', desc: '渗透测试/漏洞扫描' },
      { name: '契约测试', type: 'advanced', desc: '微服务测试策略' },
    ],
  },
  {
    id: 'ecommerce-ops',
    title: '电商运营',
    industry: '互联网/科技',
    salary: '8-18K (应届)', salaryRange: '应届8-18K → 3年15-28K → 5年25-50K (含GMV提成)',
    tags: ['平台运营', '活动策划', '数据分析', '供应链协同'],
    matchProfile: { IE: 1, TF: 0, JP: 1, SN: 0 },
    icon: '🛒',
    description: '负责电商平台的店铺运营、活动策划、流量获取和转化优化。是连接"货"和"人"的桥梁，需要数据驱动和创意策划双能。',
    personality: '需要E型的沟通驱动(对接品牌/平台/物流)和S型的执行落地。对数据敏感的同时还要有营销创意。',
    dayInLife: '09:30 看GMV/UV/转化率数据 → 11:00 活动报名/页面搭建 → 14:00 竞品分析/选品策略 → 16:30 直播排期/达人对接 → 19:00 大促期间通宵盯盘',
    companies: '阿里巴巴(淘宝/天猫)、京东、拼多多、抖音电商、快手电商、小红书、得物',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['开一个自己的闲鱼/拼多多店铺练手', '学习电商基础概念(GMV/UV/CVR/ROI)', '关注电商行业动态(亿邦动力)', '学习基础PS和Excel'] },
      sophomore: { title: '大二·基础期', items: ['系统学习平台规则(天猫/京东/抖音)', '学习直通车/钻展等推广工具', '运营一个真实店铺(哪怕小)', '学习基础SQL和数据分析'] },
      junior: { title: '大三·实战期', items: ['深入学习电商运营方法论', '掌握直播电商运营流程', '找一份电商运营实习', '参与一次618/双11大促'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递电商平台/品牌电商部', '整理运营案例和数据成果', '面试准备(数据题+运营场景题)', '关注跨境电商(TikTok Shop/Shopee)机会'] },
    },
    skills: [
      { name: '平台规则', type: 'required', desc: '熟悉淘宝/京东/抖音等平台' },
      { name: '数据分析', type: 'required', desc: 'GMV分析、转化漏斗、人群画像' },
      { name: '活动策划', type: 'required', desc: '大促方案、日常活动设计' },
      { name: '推广工具', type: 'recommended', desc: '直通车/引力魔方/千川' },
      { name: 'PS/视觉基础', type: 'recommended', desc: '商品主图/详情页/活动页面' },
      { name: '内容运营', type: 'recommended', desc: '直播/短视频/图文种草' },
      { name: '供应链理解', type: 'advanced', desc: '库存管理、物流协同' },
      { name: '跨境电商', type: 'advanced', desc: 'Shopee/TikTok/Amazon运营' },
    ],
  },
  {
    id: 'bi-engineer',
    title: '商业智能/BI工程师',
    industry: '互联网/科技',
    salary: '12-22K (应届)', salaryRange: '应届12-22K → 3年20-38K → 5年30-60K',
    tags: ['SQL', '数据仓库', 'Tableau', 'ETL'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: -1 },
    icon: '📈',
    description: '搭建企业的数据平台和BI系统，让"用数据说话"变成现实。包括数据仓库建设、ETL流程、可视化看板开发等。',
    personality: 'T型(逻辑)是核心——你需要理解数据模型、设计高效的查询。S型(务实)确保数据质量和可用性。是"数据基建"角色。',
    dayInLife: '09:30 检查数据任务是否正常 → 11:00 数据模型设计 → 14:00 ETL开发/优化 → 16:00 BI看板搭建 → 18:00 与业务对齐数据口径',
    companies: '字节跳动、阿里巴巴、腾讯、美团、快手、京东、网易、携程',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习SQL(MySQL基础)', '学习Excel高级+PowerQuery', '了解数据仓库基本概念', '学习Python基础'] },
      sophomore: { title: '大二·基础期', items: ['深入学习SQL(窗口函数/复杂查询)', '学习数据建模(星型/雪花模型)', '学习Tableau/FineBI', '了解大数据技术栈(Hadoop/Hive)'] },
      junior: { title: '大三·实战期', items: ['深入学习Hive/Spark SQL', '学习ETL工具(DataX/Kettle)', '学习数据治理方法论', '找一份数据开发/BI实习'] },
      senior: { title: '大四·冲刺期', items: ['深入学习数据仓库分层(ODS/DWD/DWS)', '秋招投递数据开发/BI工程师岗', '面试(SQL必考+数据建模+场景题)', '关注实时数仓/数据湖新技术'] },
    },
    skills: [
      { name: 'SQL', type: 'required', desc: '复杂查询、性能调优、窗口函数' },
      { name: '数据建模', type: 'required', desc: '星型模型、雪花模型、宽表设计' },
      { name: 'Hive/Spark SQL', type: 'required', desc: '大数据查询引擎' },
      { name: 'BI工具', type: 'required', desc: 'Tableau/FineBI/PowerBI' },
      { name: 'ETL流程', type: 'recommended', desc: '数据清洗、转换、调度' },
      { name: 'Python', type: 'recommended', desc: '数据处理脚本' },
      { name: '数据治理', type: 'advanced', desc: '元数据管理、数据质量' },
      { name: 'Flink/Kafka', type: 'advanced', desc: '实时数据处理' },
    ],
  },
  {
    id: 'medical-pharma-sales',
    title: '医药代表/医疗器械销售',
    industry: '医疗/医药',
    salary: '8-18K (应届+提成)', salaryRange: '应届8-18K+提成 → 3年15-30K → 5年25-50K(含业绩奖金)',
    tags: ['医药知识', '客户关系', '学术推广', '合规意识'],
    matchProfile: { IE: 2, TF: 0, JP: 0, SN: -1 },
    icon: '💊',
    description: '向医院和医生推广药品或医疗器械，通过学术交流和专业服务推动产品使用。需要医学专业知识+销售能力。',
    personality: 'E型(外向)是基础——你需要频繁拜访医生客户。S型(务实)保证合规和细节不出错。需要强大的抗压能力和自驱力。',
    dayInLife: '08:00 医院早访 → 10:00 科室会/学术宣讲 → 13:00 午餐学术交流 → 15:00 拜访新客户 → 17:30 CRM记录/日报 → 19:00 学术会议组织',
    companies: '辉瑞、罗氏、强生、美敦力、恒瑞医药、迈瑞医疗、联影医疗',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学好专业基础课(药学/临床/生物)', '了解医药行业结构和政策', '锻炼沟通表达能力', '参加医药类社团'] },
      sophomore: { title: '大二·基础期', items: ['深入学习疾病领域知识', '学习基础市场营销理论', '考取医药代表从业资格(如需要)', '参加医药公司校园活动'] },
      junior: { title: '大三·实战期', items: ['了解合规准则(RDPAC等行业规范)', '开始关注目标公司产品线', '找一份医药公司实习', '建立行业人脉'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递医药外企/头部内资', '准备行为面试(情景题+专业知识)', '了解集采政策对行业的影响', '持续学习疾病领域最新进展'] },
    },
    skills: [
      { name: '医药专业知识', type: 'required', desc: '疾病领域和产品知识' },
      { name: '沟通与演讲', type: 'required', desc: '学术宣讲和客户拜访' },
      { name: '客户管理', type: 'required', desc: 'CRM系统和客户分类' },
      { name: '合规意识', type: 'required', desc: '行业合规准则和法规' },
      { name: '英语', type: 'recommended', desc: '外企工作语言' },
      { name: '数据分析', type: 'recommended', desc: '市场和销售数据分析' },
      { name: '学术能力', type: 'advanced', desc: '解读临床文献、学术论文' },
      { name: '准入经验', type: 'advanced', desc: '招投标和进院流程' },
    ],
  },
  {
    id: 'automobile-engineer',
    title: '新能源汽车工程师',
    industry: '新能源/汽车',
    salary: '14-28K (应届)', salaryRange: '应届14-28K → 3年22-45K → 5年35-65K',
    tags: ['三电系统', '自动驾驶', 'MATLAB', 'CAN总线'],
    matchProfile: { IE: -1, TF: 2, JP: 1, SN: 1 },
    icon: '🚗',
    description: '从事新能源汽车的电池、电机、电控(三电)系统，或智能驾驶系统的研发。是中国当前最热门的硬科技赛道之一。',
    personality: 'T型(逻辑)和S型(务实)是刚需——你的代码和设计直接关系到车辆安全。需要有强烈的系统思维和质量意识。',
    dayInLife: '09:00 系统方案评审 → 10:30 Simulink建模/仿真 → 14:00 台架/路试数据分析 → 16:00 供应商技术沟通 → 18:00 技术文档/DFMEA',
    companies: '比亚迪、特斯拉、蔚来、小鹏、理想、小米汽车、华为车BU、宁德时代',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学好数学/物理/电路基础', '学习C语言和Python', '了解汽车基本构造', '关注新能源行业动态'] },
      sophomore: { title: '大二·基础期', items: ['学习自动控制原理', '学习MATLAB/Simulink', '学习嵌入式基础', '参加大学生方程式赛车(FSEC)'] },
      junior: { title: '大三·实战期', items: ['深入学习三电系统(选一个方向)', '学习CAN/LIN/车载以太网', '学习功能安全(ISO 26262)', '找一份车企或Tier1实习'] },
      senior: { title: '大四·冲刺期', items: ['深入自动驾驶/ADAS或三电方向', '秋招投递车企/零部件巨头', '读研可以大幅提升竞争力', '关注智能网联汽车最新技术趋势'] },
    },
    skills: [
      { name: 'C/C++或MATLAB', type: 'required', desc: '控制算法与仿真' },
      { name: '自动控制理论', type: 'required', desc: 'PID/MPC/状态观测器' },
      { name: '嵌入式基础', type: 'required', desc: '驱动开发与调试' },
      { name: 'CAN/LIN通信', type: 'required', desc: '车载网络协议' },
      { name: 'Simulink建模', type: 'recommended', desc: 'MBD开发流程' },
      { name: '功能安全', type: 'recommended', desc: 'ISO 26262标准' },
      { name: 'ROS/自动驾驶', type: 'advanced', desc: '感知/规划/控制算法' },
      { name: 'ASPICE', type: 'advanced', desc: '汽车软件开发流程' },
    ],
  },
  {
    id: 'legal-professional',
    title: '律师/法务',
    industry: '全行业',
    salary: '10-25K (应届)', salaryRange: '应届10-25K(红圈所更高) → 3年20-50K → 5年35-80K',
    tags: ['法律研究', '合同审查', '诉讼/仲裁', '法考'],
    matchProfile: { IE: 0, TF: 2, JP: 2, SN: -1 },
    icon: '⚖️',
    description: '为个人或企业提供法律服务，包括诉讼代理、合同审查、合规建议、知识产权保护等。需要极强的逻辑思维和文字功底。',
    personality: 'T型(逻辑分析)是律师的灵魂——你需要从海量事实中提取关键信息并构建法律论证。J型(计划)保证诉讼时间线和文书质量。',
    dayInLife: '09:00 案件材料审阅 → 10:30 客户会议/取证 → 13:30 法律文书撰写 → 16:00 法律检索/案例研究 → 18:00 合同审查 → 忙时通宵准备开庭',
    companies: '金杜、中伦、君合、方达、海问(红圈所) + 四大法务 + 大厂法务部 + 公检法',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['打好法学基础(法理学/宪法/民法总论)', '培养法律检索能力(北大法宝/威科)', '阅读经典判例', '参加模拟法庭/辩论赛'] },
      sophomore: { title: '大二·基础期', items: ['系统学习民法/刑法/行政法', '学习法律文书写作', '去法院/律所旁听和参观', '保持GPA(法学就业极看重成绩)'] },
      junior: { title: '大三·实战期', items: ['全力备战法考(客观题+主观题)', '找律所或法务实习', '确定方向(诉讼/非诉/公司法务)', '如果读研开始准备考研/保研'] },
      senior: { title: '大四·冲刺期', items: ['法考通过后全力求职', '秋招投递律所/公司法务', '准备案例分析面试', '如果没过法考,边工作边继续考'] },
    },
    skills: [
      { name: '法律职业资格证', type: 'required', desc: '律师执业的门槛' },
      { name: '法律检索', type: 'required', desc: '北大法宝/威科先行/裁判文书网' },
      { name: '法律文书', type: 'required', desc: '起诉状/答辩状/法律意见书' },
      { name: '逻辑分析', type: 'required', desc: '事实梳理与法律论证' },
      { name: '英语', type: 'recommended', desc: '涉外业务/外所工作语言' },
      { name: '合同审查', type: 'recommended', desc: '商业合同条款分析' },
      { name: '并购/上市', type: 'advanced', desc: '非诉业务的皇冠' },
      { name: '知产/数据合规', type: 'advanced', desc: '新兴热门领域' },
    ],
  },
  {
    id: 'customer-success',
    title: '客户成功经理(CSM)',
    industry: '互联网/科技',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年18-30K → 5年25-50K',
    tags: ['客户关系', 'SaaS产品', '数据分析', '培训实施'],
    matchProfile: { IE: 2, TF: -1, JP: 1, SN: -1 },
    icon: '🤲',
    description: '帮助B2B/SaaS客户用好产品，确保客户续费和增购。是"不拿提成的销售"——你的KPI是客户满意度和留存率。',
    personality: 'E型(外向沟通)和F型(共情理解)是标配——你需要成为客户的"内部代言人"。S型(务实)帮你在日常运营中稳扎稳打。',
    dayInLife: '09:30 查看客户健康度数据 → 11:00 客户QBR(季度业务回顾) → 14:00 产品培训/Onboarding → 16:00 客户问题跟踪/内部协调 → 18:00 案例沉淀',
    companies: 'Salesforce、钉钉、飞书、企业微信、用友、金蝶、北森、Moka',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['了解SaaS商业模式', '学习基础商业沟通技巧', '使用各类SaaS产品培养产品感', '阅读《硅谷蓝图》等SaaS书籍'] },
      sophomore: { title: '大二·基础期', items: ['深入学习CRM方法论', '学习基础数据分析和Excel', '练习公开演讲和PPT制作', '参与客户服务相关实习'] },
      junior: { title: '大三·实战期', items: ['系统学习客户成功方法论', '深入学习某个行业(零售/制造/金融)', '找一份CSM或客户服务实习', '考取项目管理认证(PMP)'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递SaaS公司CSM岗', '准备行为面试(情景题)', '关注国内外SaaS行业趋势', '积累行业人脉和社群'] },
    },
    skills: [
      { name: '沟通与关系管理', type: 'required', desc: '建立信任、管理预期' },
      { name: '产品理解力', type: 'required', desc: '能讲清楚产品价值和使用场景' },
      { name: '数据分析', type: 'required', desc: '客户健康度指标分析' },
      { name: '项目管理', type: 'recommended', desc: 'Onboarding流程和客户生命周期' },
      { name: '行业知识', type: 'recommended', desc: '深入理解所服务行业的痛点' },
      { name: 'PPT/演示', type: 'recommended', desc: 'QBR报告和方案展示' },
      { name: '技术理解(SQL/API)', type: 'advanced', desc: '与产品/技术团队高效对话' },
      { name: '多语言能力', type: 'advanced', desc: '服务海外客户的加分项' },
    ],
  },
  {
    id: 'content-editor',
    title: '内容编辑/主笔',
    industry: '广告/传媒',
    salary: '8-16K (应届)', salaryRange: '应届8-16K → 3年15-28K → 5年25-45K',
    tags: ['写作能力', '选题策划', '编辑审校', '行业认知'],
    matchProfile: { IE: -1, TF: -1, JP: 0, SN: 2 },
    icon: '✍️',
    description: '负责深度内容的策划、采写和编辑。在信息泛滥的时代，好内容越来越稀缺，好内容创作者也越来越值钱。',
    personality: 'N型(创新思维)帮你发现独特的选题角度，F型(感性)让你写出打动人心的文字。I型适合长时间的独立写作和阅读。',
    dayInLife: '10:00 刷热点/找选题 → 11:00 采访/调研 → 14:00 深度写作 → 17:00 编辑审校 → 19:00 阅读积累/行业交流',
    companies: '36氪、虎嗅、晚点LatePost、财新、界面、第一财经、腾讯新闻、今日头条',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['大量阅读(每天1小时以上)', '坚持写作(公众号/知乎/个人博客)', '学习基础采访技巧', '建立阅读和素材管理系统'] },
      sophomore: { title: '大二·基础期', items: ['深入学习一个垂直领域(科技/财经/文化)', '学习叙事写作方法论', '参加校媒/校报锻炼', '作品积累(公开发表30+篇)'] },
      junior: { title: '大三·实战期', items: ['产出深度长篇作品(5000字+)', '找一份媒体/内容实习', '建立行业人脉(记者/编辑)', '学习数据新闻/多媒体叙事'] },
      senior: { title: '大四·冲刺期', items: ['整理作品集(代表作5-10篇)', '秋招投递媒体/互联网内容岗', '如果条件允许,做独立内容创业', '关注AI写作工具对行业的影响'] },
    },
    skills: [
      { name: '写作能力', type: 'required', desc: '深度长文、人物特写、商业分析' },
      { name: '选题判断力', type: 'required', desc: '知道什么内容值得写' },
      { name: '采访能力', type: 'required', desc: '与人对话、挖掘故事' },
      { name: '事实核查', type: 'required', desc: '保证内容真实准确' },
      { name: '垂直领域知识', type: 'recommended', desc: '至少精通一个领域' },
      { name: 'SEO/传播', type: 'recommended', desc: '让好内容被更多人看到' },
      { name: '数据新闻', type: 'advanced', desc: '数据分析+可视化叙事' },
      { name: '英语采访', type: 'advanced', desc: '外文信息和国际采访' },
    ],
  },
  {
    id: 'architect-designer',
    title: '建筑设计师',
    industry: '房地产/建筑',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年15-28K → 5年25-50K',
    tags: ['建筑设计', 'CAD/BIM', '方案设计', '施工图'],
    matchProfile: { IE: 0, TF: 1, JP: 1, SN: 2 },
    icon: '🏗️',
    description: '从事建筑方案设计和施工图设计，从概念方案到项目落地全程参与。是在"艺术"和"工程"之间找到平衡的职业。',
    personality: 'N型(创意)让你能设计出让人惊叹的空间，S型(务实)保证方案可以落地施工。T型(逻辑)在结构和规范中很重要。',
    dayInLife: '09:30 方案草图/建模 → 11:00 甲方沟通/汇报 → 14:00 CAD施工图绘制 → 16:30 各专业协调(结构/机电) → 18:00 效果图/文本制作 → 赶图期通宵',
    companies: '中国建筑设计院、同济设计院、华东院、SOM、Aedas、gad、GOA大象设计',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['打好美术基础(素描/水彩/速写)', '学习建筑初步(空间/尺度/材料)', '大量阅读建筑案例(ArchDaily等)', '学习CAD/SketchUp基础'] },
      sophomore: { title: '大二·基础期', items: ['系统学习建筑设计原理', '学习Rhino/Grasshopper', '学习建筑史和理论', '参加建筑竞赛(新人赛/霍普杯)'] },
      junior: { title: '大三·实战期', items: ['掌握Revit/BIM技术', '深入学习建筑构造和规范', '找一份设计院实习', '完成一个有深度的课程设计'] },
      senior: { title: '大四·冲刺期', items: ['完善作品集(5+高质量项目)', '秋招投递设计院/事务所', '准备快题考试', '考证(注册建筑师,工作后)'] },
    },
    skills: [
      { name: '方案设计能力', type: 'required', desc: '概念设计到方案深化' },
      { name: 'CAD/SketchUp', type: 'required', desc: '施工图和建模' },
      { name: 'Rhino/BIM', type: 'required', desc: '复杂形体和信息化建模' },
      { name: '建筑规范', type: 'required', desc: '防火/无障碍/节能等规范' },
      { name: '渲染表达', type: 'recommended', desc: 'V-Ray/Enscape/Lumion' },
      { name: '参数化设计', type: 'recommended', desc: 'Grasshopper/Dynamo' },
      { name: '绿色建筑', type: 'advanced', desc: 'LEED/绿建标准' },
      { name: '项目全流程', type: 'advanced', desc: '从可研到竣工交付' },
    ],
  },
  {
    id: 'real-estate-planning',
    title: '房地产投资/策划',
    industry: '房地产/建筑',
    salary: '10-18K (应届)', salaryRange: '应届10-18K → 3年18-30K → 5年30-55K',
    tags: ['投资分析', '市场研究', '可行性研究', '项目定位'],
    matchProfile: { IE: 1, TF: 2, JP: 1, SN: 1 },
    icon: '🏘️',
    description: '负责房地产项目的投资分析、市场定位和产品策划。需要懂市场、会算账、能讲故事的复合型能力。',
    personality: 'T型(逻辑分析)在财务测算中至关重要，N型(创新)在产品定位中制造差异化。需要同时与投资方、设计方、营销方沟通。',
    dayInLife: '09:00 市场数据监测 → 10:30 项目可研报告 → 14:00 地块踏勘/竞品调研 → 16:00 财务测算模型 → 18:00 内部评审/汇报',
    companies: '万科、保利、华润置地、龙湖、中海、绿城、仲量联行、戴德梁行',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学习房地产基础概念', '学习Excel财务基础', '关注房地产市场动态', '阅读房地产行业研报'] },
      sophomore: { title: '大二·基础期', items: ['系统学习投资分析框架', '学习市场调研方法', '掌握财务模型(DCF/IRR)', '参加房地产相关实习'] },
      junior: { title: '大三·实战期', items: ['深入学习项目策划定位', '了解城市规划法规', '找一份房企实习', '学习PPT高质量报告制作'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递地产/咨询公司', '准备案例面试(地块测算)', '关注行业周期和就业时机', '考虑考取房地产估价师'] },
    },
    skills: [
      { name: '投资分析', type: 'required', desc: 'IRR/NPV/静态回收期测算' },
      { name: '市场研究', type: 'required', desc: '供需分析、竞品调研、客户画像' },
      { name: 'Excel建模', type: 'required', desc: '财务测算和敏感性分析' },
      { name: 'PPT报告', type: 'required', desc: '可研报告和定位报告' },
      { name: '城市规划知识', type: 'recommended', desc: '控规/详规/土地政策' },
      { name: '设计理解', type: 'recommended', desc: '强排方案和产品设计' },
      { name: 'REITs/资产证券化', type: 'advanced', desc: '不动产金融' },
      { name: 'GIS分析', type: 'advanced', desc: '地理信息系统' },
    ],
  },
  {
    id: 'translator-localization',
    title: '翻译/本地化',
    industry: '全行业',
    salary: '8-16K (应届)', salaryRange: '应届8-16K → 3年15-25K → 5年25-40K',
    tags: ['双语能力', 'CAT工具', '行业术语', '跨文化沟通'],
    matchProfile: { IE: -1, TF: 1, JP: 2, SN: -1 },
    icon: '🌐',
    description: '负责中英(或其他语种)之间的笔译、口译和本地化工作。可以是企业in-house翻译，也可以在翻译公司或做自由译者。',
    personality: 'S型(关注细节)是优秀翻译的基石——一个词的偏差可能改变整个句子的意思。J型(计划)保证按时高质量交付。I型适合长时间的笔译工作。',
    dayInLife: '09:30 笔译项目执行 → 11:00 术语库维护 → 13:30 客户原文审阅 → 15:00 翻译校对/QA → 17:00 口译/会议同传 → 自由译者时间更灵活',
    companies: '传神、中译、TransPerfect、Lionbridge、华为翻译中心、字节跳动国际化、大厂本地化团队',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['打好语言基础(英语专四专八/日语N1等)', '大量阅读目标语言的原版内容', '学习基础翻译理论', '开始双语写作练习(日记/博客)'] },
      sophomore: { title: '大二·基础期', items: ['系统学习翻译技巧(笔译)', '学习CAT工具(Trados/MemoQ)', '考翻译资格证(CATTI三级)', '做翻译志愿者/兼职积累经验'] },
      junior: { title: '大三·实战期', items: ['考取CATTI二级(含金量最高)', '积累量(目标50万字的翻译量)', '学习字幕翻译/游戏本地化等', '找一份翻译实习'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递翻译岗/本地化岗', '持续接翻译项目积累客户', '关注AI翻译对行业的影响', '培养一个行业专长(法律/医学/科技翻译)'] },
    },
    skills: [
      { name: 'CATTI证书', type: 'required', desc: '二级笔译/口译是黄金标准' },
      { name: 'Trados/MemoQ', type: 'required', desc: '主流CAT翻译工具' },
      { name: '双语写作能力', type: 'required', desc: '目标语言母语级表达' },
      { name: '行业专业知识', type: 'recommended', desc: '法律/金融/医学/科技等方向' },
      { name: '口译能力', type: 'recommended', desc: '交传/同传' },
      { name: '本地化工具', type: 'recommended', desc: 'LQA/术语管理/TMS' },
      { name: '机器翻译+PE', type: 'advanced', desc: '人机协同翻译流程' },
      { name: '第二外语', type: 'advanced', desc: '日语/韩语/德语/法语等' },
    ],
  },
  {
    id: 'risk-manager',
    title: '风险管理师',
    industry: '金融/投资',
    salary: '14-26K (应届)', salaryRange: '应届14-26K → 3年25-45K → 5年40-80K',
    tags: ['风险建模', 'FRM', '巴塞尔协议', '压力测试'],
    matchProfile: { IE: -1, TF: 2, JP: 2, SN: -1 },
    icon: '⚡',
    description: '负责识别、评估和管控金融机构面临的各类风险(信用风险、市场风险、操作风险等)。是金融机构的"守门人"角色。',
    personality: 'T型(逻辑分析)和J型(计划规范)是核心——你需要在复杂的数据中识别风险模式，并制定防控规则。',
    dayInLife: '09:00 风险指标监控 → 10:30 风险报告/仪表盘 → 13:30 模型开发/验证 → 15:30 监管合规检查 → 17:00 风险策略会议',
    companies: '五大行、招商银行、平安集团、中信证券、华泰证券、人行、银保监会',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学好数学/统计学/概率论', '学习Python或R语言', '了解金融机构运作方式', '阅读《黑天鹅》《反脆弱》'] },
      sophomore: { title: '大二·基础期', items: ['系统学习金融风险管理', '学习计量经济学和时间序列', '考FRM Part 1', '参加银行/券商风控实习'] },
      junior: { title: '大三·实战期', items: ['考完FRM Part 2 + 考虑CFA', '学习巴塞尔协议和监管框架', '深入学习信用/市场风险建模', '找一份风控相关实习'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递银行/券商/保险风控岗', '面试准备(风险案例+建模题)', '读研可大幅提升竞争力(金工/统计)', '持续跟踪监管政策变化'] },
    },
    skills: [
      { name: 'FRM证书', type: 'required', desc: '金融风险管理师' },
      { name: '统计学/计量', type: 'required', desc: 'VaR/ES/压力测试/蒙特卡洛' },
      { name: 'Python/R/SAS', type: 'required', desc: '风险建模和数据分析' },
      { name: '金融产品知识', type: 'required', desc: '衍生品/固收/信贷/外汇' },
      { name: '巴塞尔/监管', type: 'recommended', desc: '资本充足率/流动性/大额风险' },
      { name: 'SQL/数据库', type: 'recommended', desc: '风险数据集市' },
      { name: '机器学习', type: 'advanced', desc: 'AI风控/反欺诈模型' },
      { name: '气候风险', type: 'advanced', desc: 'ESG/绿色金融新兴方向' },
    ],
  },
  {
    id: 'sales-engineer',
    title: '技术销售工程师',
    industry: '制造业',
    salary: '10-20K (应届+提成)', salaryRange: '应届10-20K+提成 → 3年20-40K → 5年30-70K(含佣金)',
    tags: ['技术方案', '客户关系', '招投标', '产品演示'],
    matchProfile: { IE: 2, TF: 1, JP: 0, SN: 0 },
    icon: '🔌',
    description: '向企业客户销售技术产品或解决方案(B2B)。需要既懂技术又懂销售，能讲清楚技术价值，又能处理复杂的商务关系。',
    personality: 'E型(外向)是销售的基本盘，T型(逻辑)帮助你提供有说服力的技术方案。S型(务实)确保方案能够真正落地。',
    dayInLife: '09:00 客户拜访/产品演示 → 11:30 技术方案撰写 → 14:00 投标/报价 → 16:00 渠道/代理商沟通 → 18:00 CRM/销售预测 → 频繁出差',
    companies: '华为、思科、西门子、施耐德、海康威视、深信服、大疆行业版、Oracle',
    roadmap: {
      freshman: { title: '大一·认知期', items: ['学好专业知识(计算机/电子/机械等)', '锻炼沟通表达能力', '加入学生组织锻炼社交', '学习基础商业知识'] },
      sophomore: { title: '大二·基础期', items: ['深入学习行业/产品知识', '学习B2B销售方法论', '练习公开演讲和PPT', '参加销售相关比赛'] },
      junior: { title: '大三·实战期', items: ['深入某一行业解决方案', '了解招投标流程', '找一份销售/售前实习', '考取行业相关认证'] },
      senior: { title: '大四·冲刺期', items: ['秋招投递科技公司销售/售前岗', '面试(情景模拟+产品演示)', '持续build行业人脉', '考虑读MBA(长期)'] },
    },
    skills: [
      { name: '产品/技术知识', type: 'required', desc: '能深入浅出讲解技术方案' },
      { name: '沟通与谈判', type: 'required', desc: '理解客户需求、推动成交' },
      { name: '招投标流程', type: 'required', desc: '标书制作和投标策略' },
      { name: 'PPT演示', type: 'required', desc: '产品演示和方案展示' },
      { name: 'CRM系统', type: 'recommended', desc: 'Salesforce/销售易等' },
      { name: '行业人脉', type: 'recommended', desc: '客户和渠道资源积累' },
      { name: '英语', type: 'recommended', desc: '外企销售/海外市场' },
      { name: '方案架构', type: 'advanced', desc: '复杂项目的方案设计能力' },
    ],
  },
];

// ── Industry Overviews ───────────────────────
const INDUSTRY_OVERVIEWS = {
  '互联网/科技': {
    icon: '🌐',
    summary: '中国互联网行业经历了20年高速发展，已进入"下半场"——从消费互联网转向产业互联网，AI和大模型成为新引擎。竞争激烈但机会仍然巨大。',
    trends: ['AI/大模型重塑所有产品', '出海成为第二增长曲线', '降本增效，精益创业', '产业互联网/数字化服务崛起'],
    pros: ['薪资水平全行业领先', '成长速度快，学习密度高', '相对扁平的管理文化', '技术驱动，年轻人话语权大'],
    cons: ['加班文化普遍(996/大小周)', '竞争激烈，35岁焦虑', '行业波动大，裁员频繁', '一线城市生活成本高'],
    topCities: ['北京', '深圳', '杭州', '上海', '广州', '成都'],
    hotSkills: ['AI/大模型', 'Go/Rust', '云原生', '数据工程', 'AIGC应用'],
  },
  '金融/投资': {
    icon: '💰',
    summary: '金融行业是永远的"金饭碗"，但门槛高、竞争激烈。券商、基金、银行、保险四大板块各有千秋。量化/金融科技是近年最热方向。',
    trends: ['量化交易持续扩张', '金融科技(FinTech)重塑传统业务', '注册制改革带来投行机会', 'ESG/绿色金融兴起'],
    pros: ['薪资天花板极高', '职业发展路径清晰', '社会地位较高', '接触核心商业逻辑'],
    cons: ['入门门槛高(学历/证书)', '工作强度大(投行/研究所)', '监管趋严，合规压力大', '部分岗位重复性高'],
    topCities: ['上海', '北京', '深圳', '香港'],
    hotSkills: ['Python量化', 'CFA/FRM', '财务建模', '风控合规', '区块链'],
  },
  '公务员/事业编': {
    icon: '🏛️',
    summary: '在不确定的时代，"考编"提供了最大的确定性。国考/省考/选调生/事业单位/国企——多条路径，总有一条适合追求稳定的人。',
    trends: ['竞争逐年白热化(报录比100:1+)', '基层岗位需求增加', '数字化政府带来技术岗位', '选调生成为名校生热门选择'],
    pros: ['极高的稳定性', '完善的福利和退休保障', '社会地位和资源', '工作生活相对平衡'],
    cons: ['薪资增长有限', '晋升论资排辈', '部分岗位重复枯燥', '体制内规则复杂'],
    topCities: ['北京', '上海', '深圳', '各省会城市'],
    hotSkills: ['行测/申论', '公文写作', '政策分析', '群众工作', '财务/审计'],
  },
  '国企/央企': {
    icon: '🏭',
    summary: '国企/央企介于体制内和市场化之间——既有编制的稳定性，又有一定的市场竞争力。近年来国企改革不断深化，岗位吸引力持续上升。',
    trends: ['国企数字化转型带来大量技术岗', '混合所有制改革', '央企重组整合', '海外业务扩展(一带一路)'],
    pros: ['稳定性强于私企', '福利待遇完善', '平台大，资源丰富', '社会地位认可度高'],
    cons: ['创新空间有限', '决策链条长', '薪资弹性小', '部分企业文化老旧'],
    topCities: ['北京', '上海', '广州', '深圳', '各省会'],
    hotSkills: ['项目管理', '财务/审计', '法务/合规', '工程技术', '数字化转型'],
  },
  '快消/零售': {
    icon: '🛍️',
    summary: '快消行业是营销和管理人才的"黄埔军校"。宝洁、联合利华等巨头的管培生项目培养了无数商业领袖。新消费品牌的崛起带来了更多机会。',
    trends: ['DTC(直面消费者)模式兴起', '直播电商和社交电商爆发', '国货品牌崛起', '数字化转型(全渠道零售)'],
    pros: ['管培生培养体系成熟', '管理路线晋升清晰', '品牌营销经验值钱', '工作环境好(外企居多)'],
    cons: ['薪资增长较慢', '传统快消增速放缓', '外企在华面临本土竞争', '部分岗位天花板明显'],
    topCities: ['上海', '广州', '北京', '深圳', '杭州'],
    hotSkills: ['品牌营销', '电商运营', '数据分析', '供应链管理', '消费者洞察'],
  },
  '咨询/四大': {
    icon: '📊',
    summary: '咨询行业是商业精英的聚集地——麦肯锡、BCG、贝恩(MBB)是金字塔尖端，四大(德勤/普华永道/安永/毕马威)是最大的人才输出地。',
    trends: ['数字化转型咨询快速增长', 'ESG/可持续发展咨询兴起', 'AI咨询成为新赛道', '四大咨询业务挑战传统咨询'],
    pros: ['精英化培养体系', '薪资成长快(3年翻倍)', 'exit opportunity极好', '接触各行业top客户'],
    cons: ['工作强度极大(忙季007)', '入职门槛极高(名校+GPA)', '出差频繁(一年200+天)', '竞争压力巨大(up or out)'],
    topCities: ['上海', '北京', '深圳', '香港'],
    hotSkills: ['Case分析', '财务建模', 'PPT/Excel', '英语流利', '结构化思维'],
  },
  '制造业': {
    icon: '⚙️',
    summary: '中国是全球制造业第一大国。"中国制造2025"和产业升级推动制造业从劳动密集型向技术密集型转型，智能制造/工业4.0是核心方向。',
    trends: ['智能制造/工业4.0', '新能源汽车/动力电池爆发', '半导体/芯片国产化', '工业互联网平台'],
    pros: ['实体经济根基，抗周期', '技术积累越老越吃香', '二三线城市也有好机会', '国家政策持续支持'],
    cons: ['薪资不如互联网', '部分工厂环境较差', '学习曲线较长', '创新速度较慢'],
    topCities: ['深圳', '苏州', '上海', '东莞', '武汉', '合肥'],
    hotSkills: ['PLC/SCADA', '工业机器人', '质量管理(六西格玛)', 'ERP/MES', '嵌入式开发'],
  },
  '教育/培训': {
    icon: '📖',
    summary: '教育行业经历了"双减"的剧烈震荡后正在重新洗牌。职业教育、素质教育、教育科技(EdTech)成为新的增长方向。',
    trends: ['职业教育/产教融合受到政策鼓励', 'AI+教育(个性化学习)', '银发教育/终身学习需求增长', '素质教育(编程/艺术/体育)'],
    pros: ['有寒暑假(教师)', '社会价值和成就感', '编制内教师稳定性强', '培训行业薪资弹性大'],
    cons: ['"双减"政策冲击K12培训', '公办教师薪资增长有限', '家长/学生压力大', 'AI对教育模式的冲击'],
    topCities: ['北京', '上海', '广州', '深圳', '成都', '武汉'],
    hotSkills: ['课程设计', '教学技术(EdTech)', '学科专长', '心理学/咨询', '在线教育运营'],
  },
  '医疗/医药': {
    icon: '💉',
    summary: '医疗健康是永远的"朝阳行业"——人口老龄化、消费升级、技术创新三重驱动。医药研发、医疗器械、医疗服务、数字健康四大板块。',
    trends: ['创新药研发(生物药/基因治疗)', '医疗器械国产替代', 'AI+医疗(影像/诊断/药物发现)', '数字化医疗/互联网医院'],
    pros: ['抗周期，长期需求稳定', '技术壁垒高，越老越值钱', '政策支持力度大', '薪资在中高水平'],
    cons: ['学历门槛高(硕士起步)', '研发周期长(10年+一款药)', '合规要求严格', '医患关系紧张(医疗服务)'],
    topCities: ['上海', '北京', '苏州', '深圳', '武汉', '成都'],
    hotSkills: ['临床试验', 'GMP/GSP', '注册申报', '生物信息学', '医疗器械设计'],
  },
  '广告/传媒': {
    icon: '📺',
    summary: '内容行业正在经历从传统媒体到新媒体的彻底转型。短视频、直播、播客、AI创作——内容的形式在变，但对好内容的需求从未改变。',
    trends: ['短视频/直播成为主流', 'AI辅助创作(AIGC)', '播客/音频内容兴起', '品牌内容化(内容即广告)'],
    pros: ['创意发挥空间大', '作品有传播价值', '自由职业/远程办公友好', '门槛相对灵活'],
    cons: ['收入两极分化严重', '热点压力大，节奏快', '行业话语权向平台集中', '传统媒体持续萎缩'],
    topCities: ['北京', '上海', '杭州', '广州', '长沙'],
    hotSkills: ['短视频制作', '内容策略', 'AI创作工具', '直播运营', '社群运营'],
  },
  '新能源/汽车': {
    icon: '🔋',
    summary: '新能源汽车是中国最具全球竞争力的产业之一。电池、电机、电控、智能驾驶——每个环节都在爆发式增长，人才缺口巨大。',
    trends: ['智能驾驶(L2+/L3)加速落地', '固态电池/钠离子电池突破', '出海成为主旋律', '飞行汽车/低空经济兴起'],
    pros: ['国家战略级赛道', '薪资快速增长', '技术含量高', '产业链全球领先'],
    cons: ['行业洗牌(竞争激烈)', '部分企业加班严重', '制造端工作环境一般', '技术路线存在不确定性'],
    topCities: ['深圳', '上海', '北京', '合肥', '广州', '武汉', '长春'],
    hotSkills: ['三电系统', '自动驾驶', '功能安全', 'MATLAB/Simulink', 'ROS'],
  },
  '游戏/娱乐': {
    icon: '🎮',
    summary: '中国是全球最大的游戏市场。从手游到3A大作，从国内到出海，游戏行业正在从"流量驱动"转向"内容驱动"。',
    trends: ['精品化/3A化转型', '游戏出海(年增长20%+)', 'AI生成内容(AIGC+游戏)', '云游戏/VR游戏新体验'],
    pros: ['做自己喜欢的产品', '项目奖金丰厚', '创意和技术结合', '年轻人文化，氛围轻松'],
    cons: ['版号管制带来不确定性', '加班多(赶版本/上线)', '项目失败率高', '竞争极为激烈'],
    topCities: ['上海', '北京', '深圳', '广州', '杭州', '成都'],
    hotSkills: ['Unity/UE5', '游戏策划', '数值设计', 'AI+游戏', '技术美术(TA)'],
  },
  '房地产/建筑': {
    icon: '🏗️',
    summary: '房地产行业经历了深度调整，正从"高周转"模式转向"品质+运营"模式。虽然住宅开发降温，但城市更新、商业运营、REITs等方向仍有空间。',
    trends: ['城市更新/存量改造', '保障性住房建设', '商业地产运营(REITs)', '绿色建筑/低碳转型'],
    pros: ['项目制工作有成就感', '头部企业薪资尚可', '与城市发展紧密关联', '专业积累长期有效'],
    cons: ['行业处于下行周期', '房企暴雷风险', '加班严重(项目节点)', '政策风险大'],
    topCities: ['上海', '北京', '深圳', '广州', '杭州', '成都'],
    hotSkills: ['BIM技术', '绿色建筑', '项目管理', '投资测算', '资产运营'],
  },
};

// ── Helper: Get job by ID ────────────────────
function getJobById(id) {
  return JOB_DATABASE.find(j => j.id === id);
}

// ── Helper: Search majors (fuzzy match) ──────
function searchMajors(query) {
  const q = query.toLowerCase().trim();
  if (!q) return MAJOR_LIST.slice(0, 20);
  return MAJOR_LIST.filter(m => m.toLowerCase().includes(q));
}
